#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import xml.etree.ElementTree as ET
import os

base_path = r"C:\Users\kIrik\desktop\py\simpmusic\SimpMusic\composeApp\src\commonMain\composeResources"

# Kalan 11 dil
translations = {
    "ca": {
        "crossfade": "Encreuat",
        "crossfade_auto": "Encreuat automàtic",
        "crossfade_description": "Transició suau entre cançons",
        "crossfade_dj_mode": "Mode DJ",
        "crossfading": "Encreuat en marxa",
        "sleep_timer": "Temporitzador de son",
        "sleep_timer_description": "Atura la música després d'un temps",
        "sleep_timer_minutes": "minuts",
        "remaining_time": "Temps restant",
        "auto_backup": "Còpia de seguretat automàtica",
        "auto_backup_description": "Fes còpia de seguretat de la biblioteca periòdicament",
        "backup_frequency": "Freqüència de còpia de seguretat",
        "keep_backups": "Mantenir còpies de seguretat",
        "keep_backups_format": "Últimes {0}",
        "last_backup": "Última còpia de seguretat",
        "last_backup_time": "Executada el {0}",
        "backup_failed": "Còpia de seguretat fallida",
        "restore_backup": "Restaurar còpia de seguretat",
        "restore_backup_description": "Restaurar dades d'una còpia de seguretat anterior",
        "select_backup": "Selecciona còpia de seguretat per restaurar",
        "restore": "Restaurar",
        "backup_restored": "Còpia de seguretat restaurada",
        "upvote": "M'agrada",
        "downvote": "No m'agrada",
        "vote_for_lyrics": "Vota per lletres",
        "vote_submitted": "Gràcies per votar!",
        "rate_lyrics": "Valora les lletres",
        "select_lyrics": "Selecciona lletres",
        "discord_integration": "Integració Discord",
        "enable_rich_presence": "Habilitar presència enriquida",
        "discord_connect": "Connecta a Discord",
        "discord_disconnect": "Desconnecta de Discord",
        "connected_to_discord": "Connectat a Discord",
        "disconnected_from_discord": "Desconectat de Discord",
        "daily": "Diàriament",
        "weekly": "Setmanalment",
        "monthly": "Mensualment",
        "last_7_days": "Últims 7 dies",
        "last_30_days": "Últims 30 dies",
        "last_90_days": "Últims 90 dies",
        "export_playlist": "Exporta llista de reproducció",
        "import_playlist": "Importa llista de reproducció",
        "playlist_exported": "Llista de reproducció exportada",
        "playlist_imported": "Llista de reproducció importada",
        "lyrics_downloaded": "Lletres descarregades",
        "lyrics_not_found": "Lletres no trobades",
        "queue_clear": "Buida la cua",
        "queue_cleared": "Cua buidada",
        "queue_shuffle": "Barrreja la cua",
        "queue_repeat": "Repeteix la cua",
        "queue_repeat_one": "Repeteix una",
        "sort_by_name": "Ordena per nom",
        "sort_by_date": "Ordena per data",
        "sort_by_artist": "Ordena per artista",
        "sort_by_album": "Ordena per àlbum",
        "filter_all": "Tot",
        "filter_favorite": "Preferides",
        "filter_recently_played": "Reproduït recentment",
        "filter_most_played": "Més reproduïdes",
        "lyrics_sync": "Sincronitza lletres",
        "lyrics_sync_description": "Mostra lletres segons la cançó en riprodução",
        "enable_lyrics_sync": "Habilitar sincronització de lletres",
        "disable_lyrics_sync": "Deshabilitar sincronització de lletres",
        "lyrics_sync_enabled": "Sincronització de lletres habilitada",
        "lyrics_sync_disabled": "Sincronització de lletres deshabilitada",
        "delete_cache": "Suprimeix memòria cau",
        "delete_cache_description": "Buida dades descarregades",
        "cache_deleted": "Memòria cau suprimida",
        "check_update": "Comprova actualitzacions",
        "update_available": "Nova versió disponible",
        "update_not_available": "Utilitzes la versió més recent",
        "update_failed": "Actualització fallida",
        "about": "Quant a",
        "version": "Versió",
        "build": "Construcció",
        "changelog": "Historial de canvis",
        "open_source": "Codi obert",
        "licenses": "Llicències",
    },
    "fa": {
        "crossfade": "تمسخت",
        "crossfade_auto": "تمسخت خودکار",
        "crossfade_description": "گذار نرم بین ترانه ها",
        "crossfade_dj_mode": "حالت DJ",
        "crossfading": "تمسخت در حال انجام",
        "sleep_timer": "تایمر خواب",
        "sleep_timer_description": "موسیقی را بعد از مدت زمان مشخص شده متوقف کنید",
        "sleep_timer_minutes": "دقیقه",
        "remaining_time": "زمان باقی مانده",
        "auto_backup": "پشتیبان گیری خودکار",
        "auto_backup_description": "به طور منظم از کتابخانه خود پشتیبان بگیرید",
        "backup_frequency": "فرکانس پشتیبان گیری",
        "keep_backups": "نگاه داشتن پشتیبان ها",
        "keep_backups_format": "آخرین {0}",
        "last_backup": "آخرین پشتیبان گیری",
        "last_backup_time": "اجرا شده در {0}",
        "backup_failed": "پشتیبان گیری ناموفق",
        "restore_backup": "بازگردانی پشتیبان",
        "restore_backup_description": "داده ها را از پشتیبان قبلی بازگردانید",
        "select_backup": "پشتیبان را برای بازگردانی انتخاب کنید",
        "restore": "بازگردانی",
        "backup_restored": "پشتیبان بازگردانی شد",
        "upvote": "پسند",
        "downvote": "بدون پسند",
        "vote_for_lyrics": "رأی به ترانه",
        "vote_submitted": "از رأی شما متشکریم!",
        "rate_lyrics": "امتیاز ترانه",
        "select_lyrics": "انتخاب کلمات",
        "discord_integration": "ادغام Discord",
        "enable_rich_presence": "فعال کردن حضور غنی",
        "discord_connect": "اتصال به Discord",
        "discord_disconnect": "قطع اتصال از Discord",
        "connected_to_discord": "متصل به Discord",
        "disconnected_from_discord": "قطع اتصال از Discord",
        "daily": "روزانه",
        "weekly": "هفتگی",
        "monthly": "ماهانه",
        "last_7_days": "7 روز گذشته",
        "last_30_days": "30 روز گذشته",
        "last_90_days": "90 روز گذشته",
        "export_playlist": "صادرات فهرست پخش",
        "import_playlist": "وارد کردن فهرست پخش",
        "playlist_exported": "فهرست پخش صادر شد",
        "playlist_imported": "فهرست پخش وارد شد",
        "lyrics_downloaded": "کلمات دانلود شدند",
        "lyrics_not_found": "کلمات یافت نشدند",
        "queue_clear": "پاک کردن صف",
        "queue_cleared": "صف پاک شد",
        "queue_shuffle": "بهم ریختن صف",
        "queue_repeat": "تکرار صف",
        "queue_repeat_one": "تکرار یکی",
        "sort_by_name": "مرتب سازی بر اساس نام",
        "sort_by_date": "مرتب سازی بر اساس تاریخ",
        "sort_by_artist": "مرتب سازی بر اساس هنرمند",
        "sort_by_album": "مرتب سازی بر اساس آلبوم",
        "filter_all": "همه",
        "filter_favorite": "موارد دلخواه",
        "filter_recently_played": "اخیراً پخش شده",
        "filter_most_played": "بیشترین پخش شده",
        "lyrics_sync": "همگام سازی کلمات",
        "lyrics_sync_description": "کلمات را بر اساس ترانه ای نمایش دهید که پخش می شود",
        "enable_lyrics_sync": "فعال کردن همگام سازی کلمات",
        "disable_lyrics_sync": "غیرفعال کردن همگام سازی کلمات",
        "lyrics_sync_enabled": "همگام سازی کلمات فعال است",
        "lyrics_sync_disabled": "همگام سازی کلمات غیرفعال است",
        "delete_cache": "حذف کش",
        "delete_cache_description": "داده های دانلود شده را پاک کنید",
        "cache_deleted": "کش حذف شد",
        "check_update": "بررسی به روز رسانی ها",
        "update_available": "نسخه جدید در دسترس است",
        "update_not_available": "شما از آخرین نسخه استفاده می کنید",
        "update_failed": "به روز رسانی ناموفق",
        "about": "درباره",
        "version": "نسخه",
        "build": "ساخت",
        "changelog": "سوابق تغیی رات",
        "open_source": "منبع باز",
        "licenses": "مجوزها",
    },
    "fi": {
        "crossfade": "Ristiin häivytys",
        "crossfade_auto": "Automaattinen ristiin häivytys",
        "crossfade_description": "Sujuva siirtymä kappaleista",
        "crossfade_dj_mode": "DJ-tila",
        "crossfading": "Ristiin häivytys käynnissä",
        "sleep_timer": "Uniajastin",
        "sleep_timer_description": "Pysäytä musiikki määritetynyassa",
        "sleep_timer_minutes": "minuuttia",
        "remaining_time": "Jäljellä oleva aika",
        "auto_backup": "Automaattinen varmuuskopiointi",
        "auto_backup_description": "Tee varmuuskopio kirjastostasi säännöllisesti",
        "backup_frequency": "Varmuuskopioinnin taajuus",
        "keep_backups": "Säilytä varmuuskopiot",
        "keep_backups_format": "Viimeiset {0}",
        "last_backup": "Viimeisin varmuuskopio",
        "last_backup_time": "Suoritettu {0}",
        "backup_failed": "Varmuuskopiointi epäonnistui",
        "restore_backup": "Palauta varmuuskopio",
        "restore_backup_description": "Palauta tiedot aiemmasta varmuuskopiosta",
        "select_backup": "Valitse palautettava varmuuskopio",
        "restore": "Palauta",
        "backup_restored": "Varmuuskopio palautettu",
        "upvote": "Pidä",
        "downvote": "Älä pidä",
        "vote_for_lyrics": "Äänestä sanoituksiin",
        "vote_submitted": "Kiitos äänestämisestä!",
        "rate_lyrics": "Arvioi sanoituksia",
        "select_lyrics": "Valitse sanoitukset",
        "discord_integration": "Discord-integraatio",
        "enable_rich_presence": "Ota Rich Presence käyttöön",
        "discord_connect": "Yhdistä Discordiin",
        "discord_disconnect": "Katkaise Discord-yhteys",
        "connected_to_discord": "Yhdistetty Discordiin",
        "disconnected_from_discord": "Katkaisttu Discord-yhteydestä",
        "daily": "Päivittäin",
        "weekly": "Viikottain",
        "monthly": "Kuukausittain",
        "last_7_days": "Viimeiset 7 päivää",
        "last_30_days": "Viimeiset 30 päivää",
        "last_90_days": "Viimeiset 90 päivää",
        "export_playlist": "Vie soittolista",
        "import_playlist": "Tuo soittolista",
        "playlist_exported": "Soittolista viety",
        "playlist_imported": "Soittolista tuotu",
        "lyrics_downloaded": "Sanoitukset ladattu",
        "lyrics_not_found": "Sanoituksia ei löytynyt",
        "queue_clear": "Tyhjennä jono",
        "queue_cleared": "Jono tyhjennettiin",
        "queue_shuffle": "Sekoita jono",
        "queue_repeat": "Toista jono",
        "queue_repeat_one": "Toista yksi",
        "sort_by_name": "Lajittele nimen mukaan",
        "sort_by_date": "Lajittele päivämäärän mukaan",
        "sort_by_artist": "Lajittele artistin mukaan",
        "sort_by_album": "Lajittele albumin mukaan",
        "filter_all": "Kaikki",
        "filter_favorite": "Suosikit",
        "filter_recently_played": "Äskettäin toistettu",
        "filter_most_played": "Useimmin toistettu",
        "lyrics_sync": "Synkronoi sanoitukset",
        "lyrics_sync_description": "Näytä sanoitukset soitettavan kappaleen mukaan",
        "enable_lyrics_sync": "Ota sanoitusten synkronointi käyttöön",
        "disable_lyrics_sync": "Poista sanoitusten synkronointi käytöstä",
        "lyrics_sync_enabled": "Sanoitusten synkronointi otettu käyttöön",
        "lyrics_sync_disabled": "Sanoitusten synkronointi poistettu käytöstä",
        "delete_cache": "Poista välimuisti",
        "delete_cache_description": "Tyhjennä ladatut tiedot",
        "cache_deleted": "Välimuisti poistettu",
        "check_update": "Tarkista päivitykset",
        "update_available": "Uusi versio saatavilla",
        "update_not_available": "Käytät uusinta versiota",
        "update_failed": "Päivitys epäonnistui",
        "about": "Tietoja",
        "version": "Versio",
        "build": "Koontiversio",
        "changelog": "Muutosloki",
        "open_source": "Avoin lähdekoodi",
        "licenses": "Lisenssit",
    },
    "hi": {
        "crossfade": "क्रॉसफेड",
        "crossfade_auto": "स्वचालित क्रॉसफेड",
        "crossfade_description": "गीतों के बीच मसलिन परिवर्तन",
        "crossfade_dj_mode": "DJ मोड",
        "crossfading": "क्रॉसफेड चल रहा है",
        "sleep_timer": "नींद टाइमर",
        "sleep_timer_description": "निर्दिष्ट समय के बाद संगीत बंद करें",
        "sleep_timer_minutes": "मिनट",
        "remaining_time": "शेष समय",
        "auto_backup": "स्वचालित बैकअप",
        "auto_backup_description": "अपनी लाइब्रेरी का नियमित रूप से बैकअप लें",
        "backup_frequency": "बैकअप आवृत्ति",
        "keep_backups": "बैकअप रखें",
        "keep_backups_format": "नवीनतम {0}",
        "last_backup": "अंतिम बैकअप",
        "last_backup_time": "{0} को चलाएं",
        "backup_failed": "बैकअप विफल",
        "restore_backup": "बैकअप पुनः स्थापित करें",
        "restore_backup_description": "पिछले बैकअप से डेटा पुनः स्थापित करें",
        "select_backup": "पुनः स्थापित करने के लिए बैकअप का चयन करें",
        "restore": "पुनः स्थापित करें",
        "backup_restored": "बैकअप पुनः स्थापित किया गया",
        "upvote": "पसंद करें",
        "downvote": "पसंद न करें",
        "vote_for_lyrics": "गीत पाठ के लिए वोट दें",
        "vote_submitted": "वोट देने के लिए धन्यवाद!",
        "rate_lyrics": "गीत पाठ की रेटिंग करें",
        "select_lyrics": "गीत पाठ का चयन करें",
        "discord_integration": "Discord एकीकरण",
        "enable_rich_presence": "Rich Presence सक्षम करें",
        "discord_connect": "Discord से कनेक्ट करें",
        "discord_disconnect": "Discord से डिस्कनेक्ट करें",
        "connected_to_discord": "Discord से कनेक्ट किया गया",
        "disconnected_from_discord": "Discord से डिस्कनेक्ट किया गया",
        "daily": "दैनिक",
        "weekly": "साप्तहिक",
        "monthly": "मासिक",
        "last_7_days": "पिछले 7 दिन",
        "last_30_days": "पिछले 30 दिन",
        "last_90_days": "पिछले 90 दिन",
        "export_playlist": "प्लेलिस्ट निर्यात करें",
        "import_playlist": "प्लेलिस्ट आयात करें",
        "playlist_exported": "प्लेलिस्ट निर्यात की गई",
        "playlist_imported": "प्लेलिस्ट आयात की गई",
        "lyrics_downloaded": "गीत पाठ डाउनलोड किया गया",
        "lyrics_not_found": "गीत पाठ नहीं मिला",
        "queue_clear": "कतार साफ करें",
        "queue_cleared": "कतार साफ की गई",
        "queue_shuffle": "कतार शफल करें",
        "queue_repeat": "कतार दोहराएं",
        "queue_repeat_one": "एक दोहराएं",
        "sort_by_name": "नाम से क्रमबद्ध करें",
        "sort_by_date": "तारीख से क्रमबद्ध करें",
        "sort_by_artist": "कलाकार से क्रमबद्ध करें",
        "sort_by_album": "एलबम से क्रमबद्ध करें",
        "filter_all": "सभी",
        "filter_favorite": "पसंदीदा",
        "filter_recently_played": "हाल ही में बजाया गया",
        "filter_most_played": "सबसे अधिक बजाया गया",
        "lyrics_sync": "गीत पाठ सिंक्रोनाइज करें",
        "lyrics_sync_description": "बजाए जा रहे गीत के अनुसार गीत पाठ दिखाएं",
        "enable_lyrics_sync": "गीत पाठ सिंक्रोनाइज़ेशन सक्षम करें",
        "disable_lyrics_sync": "गीत पाठ सिंक्रोनाइज़ेशन अक्षम करें",
        "lyrics_sync_enabled": "गीत पाठ सिंक्रोनाइज़ेशन सक्षम है",
        "lyrics_sync_disabled": "गीत पाठ सिंक्रोनाइज़ेशन अक्षम है",
        "delete_cache": "कैश हटाएं",
        "delete_cache_description": "डाउनलोड किए गए डेटा को साफ करें",
        "cache_deleted": "कैश हटाया गया",
        "check_update": "अपडेट जांचें",
        "update_available": "नया संस्करण उपलब्ध है",
        "update_not_available": "आप नवीनतम संस्करण का उपयोग कर रहे हैं",
        "update_failed": "अपडेट विफल",
        "about": "के बारे में",
        "version": "संस्करण",
        "build": "निर्माण",
        "changelog": "परिवर्तन लॉग",
        "open_source": "खुला स्रोत",
        "licenses": "लाइसेंस",
    },
    "nl": {
        "crossfade": "Crossfade",
        "crossfade_auto": "Automatische crossfade",
        "crossfade_description": "Vloeiende overgang tussen nummers",
        "crossfade_dj_mode": "DJ-modus",
        "crossfading": "Crossfade bezig",
        "sleep_timer": "Slaaptimer",
        "sleep_timer_description": "Muziek stoppen na bepaalde tijd",
        "sleep_timer_minutes": "minuten",
        "remaining_time": "Resterende tijd",
        "auto_backup": "Automatische back-up",
        "auto_backup_description": "Maak regelmatig een back-up van uw bibliotheek",
        "backup_frequency": "Back-up frequentie",
        "keep_backups": "Back-ups behouden",
        "keep_backups_format": "Nieuwste {0}",
        "last_backup": "Laatste back-up",
        "last_backup_time": "Uitgevoerd op {0}",
        "backup_failed": "Back-up mislukt",
        "restore_backup": "Back-up herstellen",
        "restore_backup_description": "Gegevens herstellen uit eerdere back-up",
        "select_backup": "Selecteer back-up om te herstellen",
        "restore": "Herstellen",
        "backup_restored": "Back-up hersteld",
        "upvote": "Leuk",
        "downvote": "Niet leuk",
        "vote_for_lyrics": "Stem op nummertekst",
        "vote_submitted": "Dank u voor uw stem!",
        "rate_lyrics": "Nummertekst beoordelen",
        "select_lyrics": "Selecteer nummertekst",
        "discord_integration": "Discord-integratie",
        "enable_rich_presence": "Rich Presence inschakelen",
        "discord_connect": "Verbinden met Discord",
        "discord_disconnect": "Verbinding met Discord verbreken",
        "connected_to_discord": "Met Discord verbonden",
        "disconnected_from_discord": "Verbinding met Discord verbroken",
        "daily": "Dagelijks",
        "weekly": "Wekelijks",
        "monthly": "Maandelijks",
        "last_7_days": "Afgelopen 7 dagen",
        "last_30_days": "Afgelopen 30 dagen",
        "last_90_days": "Afgelopen 90 dagen",
        "export_playlist": "Speellijst exporteren",
        "import_playlist": "Speellijst importeren",
        "playlist_exported": "Speellijst geëxporteerd",
        "playlist_imported": "Speellijst geïmporteerd",
        "lyrics_downloaded": "Nummertekst gedownload",
        "lyrics_not_found": "Nummertekst niet gevonden",
        "queue_clear": "Wachtrij wissen",
        "queue_cleared": "Wachtrij gewist",
        "queue_shuffle": "Wachtrij schudden",
        "queue_repeat": "Wachtrij herhalen",
        "queue_repeat_one": "Eén herhalen",
        "sort_by_name": "Sorteren op naam",
        "sort_by_date": "Sorteren op datum",
        "sort_by_artist": "Sorteren op artiest",
        "sort_by_album": "Sorteren op album",
        "filter_all": "Alles",
        "filter_favorite": "Favorieten",
        "filter_recently_played": "Onlangs afgespeeld",
        "filter_most_played": "Meest afgespeeld",
        "lyrics_sync": "Nummertekst synchroniseren",
        "lyrics_sync_description": "Nummertekst weergeven afhankelijk van afgespeelde nummer",
        "enable_lyrics_sync": "Nummertekstsynchronisatie inschakelen",
        "disable_lyrics_sync": "Nummertekstsynchronisatie uitschakelen",
        "lyrics_sync_enabled": "Nummertekstsynchronisatie ingeschakeld",
        "lyrics_sync_disabled": "Nummertekstsynchronisatie uitgeschakeld",
        "delete_cache": "Cache wissen",
        "delete_cache_description": "Gedownloade gegevens verwijderen",
        "cache_deleted": "Cache verwijderd",
        "check_update": "Updates controleren",
        "update_available": "Nieuwe versie beschikbaar",
        "update_not_available": "U gebruikt de nieuwste versie",
        "update_failed": "Update mislukt",
        "about": "Over",
        "version": "Versie",
        "build": "Build",
        "changelog": "Wijzigingenlogboek",
        "open_source": "Open source",
        "licenses": "Licenties",
    },
    "pl": {
        "crossfade": "Przejście",
        "crossfade_auto": "Automatyczne przejście",
        "crossfade_description": "Płynne przejście między utworami",
        "crossfade_dj_mode": "Tryb DJ",
        "crossfading": "Przejście aktywne",
        "sleep_timer": "Czasomierz snu",
        "sleep_timer_description": "Zatrzymaj muzykę po określonym czasie",
        "sleep_timer_minutes": "minut",
        "remaining_time": "Pozostały czas",
        "auto_backup": "Automatyczna kopia zapasowa",
        "auto_backup_description": "Regularnie twórz kopię zapasową swojej biblioteki",
        "backup_frequency": "Częstość tworzenia kopii",
        "keep_backups": "Zachowaj kopie zapasowe",
        "keep_backups_format": "Ostatnie {0}",
        "last_backup": "Ostatnia kopia zapasowa",
        "last_backup_time": "Uruchomiono {0}",
        "backup_failed": "Kopia zapasowa nieudana",
        "restore_backup": "Przywróć kopię zapasową",
        "restore_backup_description": "Przywróć dane z poprzedniej kopii zapasowej",
        "select_backup": "Wybierz kopię zapasową do przywrócenia",
        "restore": "Przywróć",
        "backup_restored": "Kopia zapasowa przywrócona",
        "upvote": "Lubię",
        "downvote": "Nie lubię",
        "vote_for_lyrics": "Głosuj na tekst",
        "vote_submitted": "Dziękujemy za głos!",
        "rate_lyrics": "Oceń tekst",
        "select_lyrics": "Wybierz tekst",
        "discord_integration": "Integracja z Discord",
        "enable_rich_presence": "Włącz Rich Presence",
        "discord_connect": "Połącz się z Discord",
        "discord_disconnect": "Rozłącz się z Discord",
        "connected_to_discord": "Połączono z Discord",
        "disconnected_from_discord": "Rozłączono z Discord",
        "daily": "Codziennie",
        "weekly": "Co tydzień",
        "monthly": "Co miesiąc",
        "last_7_days": "Ostatnie 7 dni",
        "last_30_days": "Ostatnie 30 dni",
        "last_90_days": "Ostatnie 90 dni",
        "export_playlist": "Eksportuj playlistę",
        "import_playlist": "Importuj playlistę",
        "playlist_exported": "Playlista wyeksportowana",
        "playlist_imported": "Playlista zaimportowana",
        "lyrics_downloaded": "Tekst pobrany",
        "lyrics_not_found": "Tekst nie znaleziony",
        "queue_clear": "Wyczyść kolejkę",
        "queue_cleared": "Kolejka wyczyszczona",
        "queue_shuffle": "Potasuj kolejkę",
        "queue_repeat": "Powtórz kolejkę",
        "queue_repeat_one": "Powtórz jeden",
        "sort_by_name": "Sortuj po nazwie",
        "sort_by_date": "Sortuj po dacie",
        "sort_by_artist": "Sortuj po artyście",
        "sort_by_album": "Sortuj po albumie",
        "filter_all": "Wszystkie",
        "filter_favorite": "Ulubione",
        "filter_recently_played": "Niedawno odtwarzane",
        "filter_most_played": "Najczęściej odtwarzane",
        "lyrics_sync": "Synchronizuj tekst",
        "lyrics_sync_description": "Wyświetlaj tekst w stosunku do odtwarzanego utworu",
        "enable_lyrics_sync": "Włącz synchronizację tekstu",
        "disable_lyrics_sync": "Wyłącz synchronizację tekstu",
        "lyrics_sync_enabled": "Synchronizacja tekstu włączona",
        "lyrics_sync_disabled": "Synchronizacja tekstu wyłączona",
        "delete_cache": "Usuń pamięć podręczną",
        "delete_cache_description": "Wyczyść pobrane dane",
        "cache_deleted": "Pamięć podręczna usunięta",
        "check_update": "Sprawdź aktualizacje",
        "update_available": "Dostępna nowa wersja",
        "update_not_available": "Używasz najnowszej wersji",
        "update_failed": "Aktualizacja nieudana",
        "about": "O programie",
        "version": "Wersja",
        "build": "Kompilacja",
        "changelog": "Lista zmian",
        "open_source": "Kod otwarty",
        "licenses": "Licencje",
    },
    "th": {
        "crossfade": "ครอสเฟด",
        "crossfade_auto": "ครอสเฟดอัตโนมัติ",
        "crossfade_description": "การเปลี่ยนผ่านที่นุ่มนวลระหว่างเพลง",
        "crossfade_dj_mode": "โหมด DJ",
        "crossfading": "ครอสเฟดกำลังทำงาน",
        "sleep_timer": "ตั้งเวลานอน",
        "sleep_timer_description": "หยุดเพลงหลังจากเวลาที่กำหนด",
        "sleep_timer_minutes": "นาที",
        "remaining_time": "เวลาคงเหลือ",
        "auto_backup": "การสำรองข้อมูลอัตโนมัติ",
        "auto_backup_description": "สำรองข้อมูลไลบรารีของคุณเป็นระยะ",
        "backup_frequency": "ความถี่การสำรองข้อมูล",
        "keep_backups": "เก็บสำรองข้อมูล",
        "keep_backups_format": "ล่าสุด {0}",
        "last_backup": "การสำรองข้อมูลครั้งสุดท้าย",
        "last_backup_time": "ดำเนินการเมื่อ {0}",
        "backup_failed": "การสำรองข้อมูลล้มเหลว",
        "restore_backup": "คืนค่าจากสำรองข้อมูล",
        "restore_backup_description": "คืนค่าข้อมูลจากการสำรองข้อมูลที่ผ่านมา",
        "select_backup": "เลือกการสำรองข้อมูลที่จะคืนค่า",
        "restore": "คืนค่า",
        "backup_restored": "คืนค่าจากสำรองข้อมูลแล้ว",
        "upvote": "ชอบ",
        "downvote": "ไม่ชอบ",
        "vote_for_lyrics": "โหวตเลือกเนื้อร้อง",
        "vote_submitted": "ขอบคุณที่โหวต!",
        "rate_lyrics": "อัตราคะแนนเนื้อร้อง",
        "select_lyrics": "เลือกเนื้อร้อง",
        "discord_integration": "การรวม Discord",
        "enable_rich_presence": "เปิดใช้ Rich Presence",
        "discord_connect": "เชื่อมต่อกับ Discord",
        "discord_disconnect": "ยกเลิกการเชื่อมต่อจาก Discord",
        "connected_to_discord": "เชื่อมต่อกับ Discord",
        "disconnected_from_discord": "ยกเลิกการเชื่อมต่อจาก Discord",
        "daily": "ทุกวัน",
        "weekly": "ทุกสัปดาห์",
        "monthly": "ทุกเดือน",
        "last_7_days": "7 วันที่ผ่านมา",
        "last_30_days": "30 วันที่ผ่านมา",
        "last_90_days": "90 วันที่ผ่านมา",
        "export_playlist": "ส่งออกรายการเพลง",
        "import_playlist": "นำเข้ารายการเพลง",
        "playlist_exported": "ส่งออกรายการเพลงแล้ว",
        "playlist_imported": "นำเข้ารายการเพลงแล้ว",
        "lyrics_downloaded": "ดาวน์โหลดเนื้อร้องแล้ว",
        "lyrics_not_found": "ไม่พบเนื้อร้อง",
        "queue_clear": "ล้างคิว",
        "queue_cleared": "ล้างคิวแล้ว",
        "queue_shuffle": "สุ่มคิว",
        "queue_repeat": "ทำซ้ำคิว",
        "queue_repeat_one": "ทำซ้ำหนึ่ง",
        "sort_by_name": "เรียงตามชื่อ",
        "sort_by_date": "เรียงตามวันที่",
        "sort_by_artist": "เรียงตามศิลปิน",
        "sort_by_album": "เรียงตามอัลบัม",
        "filter_all": "ทั้งหมด",
        "filter_favorite": "รายการโปรด",
        "filter_recently_played": "เล่นเมื่อไม่นาน",
        "filter_most_played": "เล่นมากที่สุด",
        "lyrics_sync": "ซิงค์เนื้อร้อง",
        "lyrics_sync_description": "แสดงเนื้อร้องตามเพลงที่กำลังเล่น",
        "enable_lyrics_sync": "เปิดใช้การซิงค์เนื้อร้อง",
        "disable_lyrics_sync": "ปิดใช้การซิงค์เนื้อร้อง",
        "lyrics_sync_enabled": "การซิงค์เนื้อร้องเปิดอยู่",
        "lyrics_sync_disabled": "การซิงค์เนื้อร้องปิดอยู่",
        "delete_cache": "ลบแคช",
        "delete_cache_description": "ล้างข้อมูลที่ดาวน์โหลด",
        "cache_deleted": "ลบแคชแล้ว",
        "check_update": "ตรวจสอบการอัปเดต",
        "update_available": "มีรุ่นใหม่ให้ใช้งาน",
        "update_not_available": "คุณใช้รุ่นล่าสุด",
        "update_failed": "การอัปเดตล้มเหลว",
        "about": "เกี่ยวกับ",
        "version": "เวอร์ชัน",
        "build": "การสร้าง",
        "changelog": "บันทึกการเปลี่ยนแปลง",
        "open_source": "โอเพนโซร์ส",
        "licenses": "ใบอนุญาต",
    },
    "uk": {
        "crossfade": "Плавний перехід",
        "crossfade_auto": "Автоматичний плавний перехід",
        "crossfade_description": "Плавна переходу між мелодіями",
        "crossfade_dj_mode": "Режим диджея",
        "crossfading": "Плавний перехід активний",
        "sleep_timer": "Таймер сну",
        "sleep_timer_description": "Зупинити музику через задану часу",
        "sleep_timer_minutes": "хвилин",
        "remaining_time": "Залишилося часу",
        "auto_backup": "Автоматична резервна копія",
        "auto_backup_description": "Регулярно створюйте резервні копії своєї бібліотеки",
        "backup_frequency": "Частота резервного копіювання",
        "keep_backups": "Зберігати резервні копії",
        "keep_backups_format": "Останні {0}",
        "last_backup": "Остання резервна копія",
        "last_backup_time": "Виконано {0}",
        "backup_failed": "Резервна копія невдала",
        "restore_backup": "Відновити резервну копію",
        "restore_backup_description": "Відновіть дані з попередньої резервної копії",
        "select_backup": "Виберіть резервну копію для відновлення",
        "restore": "Відновити",
        "backup_restored": "Резервна копія відновлена",
        "upvote": "Вподобати",
        "downvote": "Не вподобати",
        "vote_for_lyrics": "Голосувати за текст",
        "vote_submitted": "Спасибі за ваш голос!",
        "rate_lyrics": "Оцінити текст",
        "select_lyrics": "Вибрати текст",
        "discord_integration": "Інтеграція Discord",
        "enable_rich_presence": "Увімкнути Rich Presence",
        "discord_connect": "Підключитися до Discord",
        "discord_disconnect": "Відключитися від Discord",
        "connected_to_discord": "Підключено до Discord",
        "disconnected_from_discord": "Відключено від Discord",
        "daily": "Щоденно",
        "weekly": "Щотижня",
        "monthly": "Щомісяця",
        "last_7_days": "Останні 7 днів",
        "last_30_days": "Останні 30 днів",
        "last_90_days": "Останні 90 днів",
        "export_playlist": "Експортувати плейлист",
        "import_playlist": "Імпортувати плейлист",
        "playlist_exported": "Плейлист експортовано",
        "playlist_imported": "Плейлист імпортовано",
        "lyrics_downloaded": "Текст завантажено",
        "lyrics_not_found": "Текст не знайдено",
        "queue_clear": "Очистити чергу",
        "queue_cleared": "Чергу очищено",
        "queue_shuffle": "Перемішати чергу",
        "queue_repeat": "Повторити чергу",
        "queue_repeat_one": "Повторити один",
        "sort_by_name": "Сортувати за назвою",
        "sort_by_date": "Сортувати за датою",
        "sort_by_artist": "Сортувати за виконавцем",
        "sort_by_album": "Сортувати за альбомом",
        "filter_all": "Усі",
        "filter_favorite": "Вибране",
        "filter_recently_played": "Недавно відтворені",
        "filter_most_played": "Найбільше відтворені",
        "lyrics_sync": "Синхронізувати текст",
        "lyrics_sync_description": "Показувати текст відповідно до пісні, яка відтворюється",
        "enable_lyrics_sync": "Увімкнути синхронізацію тексту",
        "disable_lyrics_sync": "Вимкнути синхронізацію тексту",
        "lyrics_sync_enabled": "Синхронізація тексту увімкнена",
        "lyrics_sync_disabled": "Синхронізація тексту вимкнена",
        "delete_cache": "Видалити кеш",
        "delete_cache_description": "Очистити завантажені дані",
        "cache_deleted": "Кеш видалено",
        "check_update": "Перевірити оновлення",
        "update_available": "Доступна нова версія",
        "update_not_available": "Ви користуєтесь останньою версією",
        "update_failed": "Оновлення невдало",
        "about": "Про",
        "version": "Версія",
        "build": "Збірка",
        "changelog": "Журнал змін",
        "open_source": "Відкритий код",
        "licenses": "Ліцензії",
    },
    "vi": {
        "crossfade": "Chuyển tiếp",
        "crossfade_auto": "Chuyển tiếp tự động",
        "crossfade_description": "Chuyển tiếp mềm mại giữa các bài hát",
        "crossfade_dj_mode": "Chế độ DJ",
        "crossfading": "Chuyển tiếp đang hoạt động",
        "sleep_timer": "Bộ hẹn giờ ngủ",
        "sleep_timer_description": "Dừng nhạc sau thời gian được chỉ định",
        "sleep_timer_minutes": "phút",
        "remaining_time": "Thời gian còn lại",
        "auto_backup": "Sao lưu tự động",
        "auto_backup_description": "Sao lưu thư viện của bạn định kỳ",
        "backup_frequency": "Tần suất sao lưu",
        "keep_backups": "Giữ sao lưu",
        "keep_backups_format": "Mới nhất {0}",
        "last_backup": "Lần sao lưu gần đây nhất",
        "last_backup_time": "Chạy lúc {0}",
        "backup_failed": "Sao lưu không thành công",
        "restore_backup": "Khôi phục sao lưu",
        "restore_backup_description": "Khôi phục dữ liệu từ sao lưu trước đó",
        "select_backup": "Chọn sao lưu để khôi phục",
        "restore": "Khôi phục",
        "backup_restored": "Đã khôi phục sao lưu",
        "upvote": "Thích",
        "downvote": "Không thích",
        "vote_for_lyrics": "Bình chọn lời bài hát",
        "vote_submitted": "Cảm ơn bạn đã bình chọn!",
        "rate_lyrics": "Đánh giá lời bài hát",
        "select_lyrics": "Chọn lời bài hát",
        "discord_integration": "Tích hợp Discord",
        "enable_rich_presence": "Bật Rich Presence",
        "discord_connect": "Kết nối với Discord",
        "discord_disconnect": "Ngắt kết nối từ Discord",
        "connected_to_discord": "Đã kết nối với Discord",
        "disconnected_from_discord": "Đã ngắt kết nối từ Discord",
        "daily": "Hàng ngày",
        "weekly": "Hàng tuần",
        "monthly": "Hàng tháng",
        "last_7_days": "7 ngày qua",
        "last_30_days": "30 ngày qua",
        "last_90_days": "90 ngày qua",
        "export_playlist": "Xuất danh sách phát",
        "import_playlist": "Nhập danh sách phát",
        "playlist_exported": "Đã xuất danh sách phát",
        "playlist_imported": "Đã nhập danh sách phát",
        "lyrics_downloaded": "Đã tải xuống lời bài hát",
        "lyrics_not_found": "Không tìm thấy lời bài hát",
        "queue_clear": "Xóa hàng đợi",
        "queue_cleared": "Đã xóa hàng đợi",
        "queue_shuffle": "Xáo trộn hàng đợi",
        "queue_repeat": "Lặp lại hàng đợi",
        "queue_repeat_one": "Lặp lại một",
        "sort_by_name": "Sắp xếp theo tên",
        "sort_by_date": "Sắp xếp theo ngày",
        "sort_by_artist": "Sắp xếp theo nghệ sĩ",
        "sort_by_album": "Sắp xếp theo album",
        "filter_all": "Tất cả",
        "filter_favorite": "Yêu thích",
        "filter_recently_played": "Vừa phát",
        "filter_most_played": "Phát nhiều nhất",
        "lyrics_sync": "Đồng bộ hóa lời bài hát",
        "lyrics_sync_description": "Hiển thị lời bài hát theo bài hát đang phát",
        "enable_lyrics_sync": "Bật đồng bộ hóa lời bài hát",
        "disable_lyrics_sync": "Tắt đồng bộ hóa lời bài hát",
        "lyrics_sync_enabled": "Đồng bộ hóa lời bài hát đã bật",
        "lyrics_sync_disabled": "Đồng bộ hóa lời bài hát đã tắt",
        "delete_cache": "Xóa bộ nhớ đệm",
        "delete_cache_description": "Xóa dữ liệu đã tải xuống",
        "cache_deleted": "Đã xóa bộ nhớ đệm",
        "check_update": "Kiểm tra cập nhật",
        "update_available": "Phiên bản mới có sẵn",
        "update_not_available": "Bạn đang sử dụng phiên bản mới nhất",
        "update_failed": "Cập nhật không thành công",
        "about": "Giới thiệu",
        "version": "Phiên bản",
        "build": "Bản dựng",
        "changelog": "Nhật ký thay đổi",
        "open_source": "Mã nguồn mở",
        "licenses": "Giấy phép",
    },
    "ar": {
        "crossfade": "تقاطع",
        "crossfade_auto": "تقاطع تلقائي",
        "crossfade_description": "انتقال سلس بين المقاطع",
        "crossfade_dj_mode": "وضع DJ",
        "crossfading": "تقاطع قيد التشغيل",
        "sleep_timer": "مؤقت النوم",
        "sleep_timer_description": "إيقاف الموسيقى بعد فترة زمنية محددة",
        "sleep_timer_minutes": "دقائق",
        "remaining_time": "الوقت المتبقي",
        "auto_backup": "النسخ الاحتياطي التلقائي",
        "auto_backup_description": "قم بعمل نسخ احتياطية من مكتبتك بشكل دوري",
        "backup_frequency": "تكرار النسخ الاحتياطي",
        "keep_backups": "الاحتفاظ بالنسخ الاحتياطية",
        "keep_backups_format": "آخر {0}",
        "last_backup": "آخر نسخة احتياطية",
        "last_backup_time": "تم التشغيل {0}",
        "backup_failed": "فشل النسخ الاحتياطي",
        "restore_backup": "استعادة النسخة الاحتياطية",
        "restore_backup_description": "استعادة البيانات من نسخة احتياطية سابقة",
        "select_backup": "حدد النسخة الاحتياطية لاستعادتها",
        "restore": "استعادة",
        "backup_restored": "تم استعادة النسخة الاحتياطية",
        "upvote": "إعجاب",
        "downvote": "عدم إعجاب",
        "vote_for_lyrics": "صوت للكلمات",
        "vote_submitted": "شكراً لتصويتك!",
        "rate_lyrics": "تقييم الكلمات",
        "select_lyrics": "حدد الكلمات",
        "discord_integration": "تكامل Discord",
        "enable_rich_presence": "تفعيل Rich Presence",
        "discord_connect": "الاتصال بـ Discord",
        "discord_disconnect": "قطع الاتصال عن Discord",
        "connected_to_discord": "متصل بـ Discord",
        "disconnected_from_discord": "غير متصل بـ Discord",
        "daily": "يومياً",
        "weekly": "أسبوعياً",
        "monthly": "شهرياً",
        "last_7_days": "آخر 7 أيام",
        "last_30_days": "آخر 30 يوماً",
        "last_90_days": "آخر 90 يوماً",
        "export_playlist": "تصدير قائمة التشغيل",
        "import_playlist": "استيراد قائمة التشغيل",
        "playlist_exported": "تم تصدير قائمة التشغيل",
        "playlist_imported": "تم استيراد قائمة التشغيل",
        "lyrics_downloaded": "تم تنزيل الكلمات",
        "lyrics_not_found": "لم يتم العثور على الكلمات",
        "queue_clear": "مسح قائمة الانتظار",
        "queue_cleared": "تم مسح قائمة الانتظار",
        "queue_shuffle": "خلط قائمة الانتظار",
        "queue_repeat": "تكرار قائمة الانتظار",
        "queue_repeat_one": "تكرار واحد",
        "sort_by_name": "الترتيب حسب الاسم",
        "sort_by_date": "الترتيب حسب التاريخ",
        "sort_by_artist": "الترتيب حسب الفنان",
        "sort_by_album": "الترتيب حسب الألبوم",
        "filter_all": "الكل",
        "filter_favorite": "المفضلة",
        "filter_recently_played": "المُشغّلة مؤخراً",
        "filter_most_played": "الأكثر تشغيلاً",
        "lyrics_sync": "مزامنة الكلمات",
        "lyrics_sync_description": "عرض الكلمات وفقاً للأغنية التي يتم تشغيلها",
        "enable_lyrics_sync": "تفعيل مزامنة الكلمات",
        "disable_lyrics_sync": "تعطيل مزامنة الكلمات",
        "lyrics_sync_enabled": "مزامنة الكلمات مفعلة",
        "lyrics_sync_disabled": "مزامنة الكلمات معطلة",
        "delete_cache": "حذف الذاكرة المؤقتة",
        "delete_cache_description": "مسح البيانات المُنزلة",
        "cache_deleted": "تم حذف الذاكرة المؤقتة",
        "check_update": "التحقق من التحديثات",
        "update_available": "إصدار جديد متاح",
        "update_not_available": "أنت تستخدم أحدث إصدار",
        "update_failed": "فشل التحديث",
        "about": "حول",
        "version": "الإصدار",
        "build": "الإنشاء",
        "changelog": "سجل التغييرات",
        "open_source": "مصدر مفتوح",
        "licenses": "الرخص",
    },
}

for lang_code, trans_dict in translations.items():
    lang_dir = os.path.join(base_path, f"values-{lang_code}")
    strings_file = os.path.join(lang_dir, "strings.xml")
    
    if not os.path.exists(strings_file):
        print(f"SKIP {lang_code}: Dosya bulunamadı")
        continue
    
    # Mevcut XML'i oku
    tree = ET.parse(strings_file)
    root = tree.getroot()
    
    # Var olan key'leri bul
    existing_keys = set()
    for string_elem in root.findall("string"):
        key = string_elem.get("name")
        if key:
            existing_keys.add(key)
    
    # Eksik çevirileri ekle
    added = 0
    for key, value in trans_dict.items():
        if key not in existing_keys:
            new_elem = ET.Element("string")
            new_elem.set("name", key)
            new_elem.text = value
            root.append(new_elem)
            added += 1
    
    # XML'i kaydet
    tree.write(strings_file, encoding="utf-8", xml_declaration=True)
    
    final_count = len(root.findall("string"))
    print(f"✓ {lang_code}: +{added} → {final_count} toplam çeviri")

print("\n✅ Tüm 11 dil tamamlandı!")
