#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import xml.etree.ElementTree as ET
import os

base_path = r"C:\Users\kIrik\desktop\py\simpmusic\SimpMusic\composeApp\src\commonMain\composeResources"

# 86 eksik çeviriler - tüm dillerle
translations = {
    "ja": {
        "crossfade": "クロスフェード",
        "crossfade_auto": "自動クロスフェード",
        "crossfade_description": "トラック間のスムーズな遷移",
        "crossfade_dj_mode": "DJモード",
        "crossfading": "クロスフェード実行中",
        "sleep_timer": "スリープタイマー",
        "sleep_timer_description": "指定時間後に音楽を停止",
        "sleep_timer_minutes": "分",
        "remaining_time": "残り時間",
        "auto_backup": "自動バックアップ",
        "auto_backup_description": "ライブラリを定期的にバックアップ",
        "backup_frequency": "バックアップ頻度",
        "keep_backups": "バックアップを保持",
        "keep_backups_format": "最新の{0}個",
        "last_backup": "最後のバックアップ",
        "last_backup_time": "{0}に実行",
        "backup_failed": "バックアップに失敗",
        "restore_backup": "バックアップから復元",
        "restore_backup_description": "以前のバックアップからデータを復元",
        "select_backup": "復元するバックアップを選択",
        "restore": "復元",
        "backup_restored": "バックアップを復元しました",
        "upvote": "高評価",
        "downvote": "低評価",
        "vote_for_lyrics": "歌詞に投票",
        "vote_submitted": "投票をありがとうございました！",
        "rate_lyrics": "歌詞を評価",
        "select_lyrics": "歌詞を選択",
        "discord_integration": "Discord統合",
        "enable_rich_presence": "リッチプレゼンスを有効化",
        "discord_connect": "Discordに接続",
        "discord_disconnect": "Discordから切断",
        "connected_to_discord": "Discordに接続しました",
        "disconnected_from_discord": "Discordから切断しました",
        "daily": "毎日",
        "weekly": "毎週",
        "monthly": "毎月",
        "last_7_days": "過去7日間",
        "last_30_days": "過去30日間",
        "last_90_days": "過去90日間",
        "export_playlist": "プレイリストをエクスポート",
        "import_playlist": "プレイリストをインポート",
        "playlist_exported": "プレイリストをエクスポートしました",
        "playlist_imported": "プレイリストをインポートしました",
        "lyrics_downloaded": "歌詞をダウンロードしました",
        "lyrics_not_found": "歌詞が見つかりません",
        "queue_clear": "キューをクリア",
        "queue_cleared": "キューをクリアしました",
        "queue_shuffle": "キューをシャッフル",
        "queue_repeat": "キューを繰り返す",
        "queue_repeat_one": "1つを繰り返す",
        "sort_by_name": "名前順",
        "sort_by_date": "日付順",
        "sort_by_artist": "アーティスト順",
        "sort_by_album": "アルバム順",
        "filter_all": "すべて",
        "filter_favorite": "お気に入り",
        "filter_recently_played": "最近再生した",
        "filter_most_played": "最も再生した",
        "lyrics_sync": "歌詞を同期",
        "lyrics_sync_description": "再生中の曲に合わせて歌詞を表示",
        "enable_lyrics_sync": "歌詞同期を有効化",
        "disable_lyrics_sync": "歌詞同期を無効化",
        "lyrics_sync_enabled": "歌詞同期が有効です",
        "lyrics_sync_disabled": "歌詞同期が無効です",
        "delete_cache": "キャッシュを削除",
        "delete_cache_description": "ダウンロード済みデータをクリア",
        "cache_deleted": "キャッシュを削除しました",
        "check_update": "アップデートを確認",
        "update_available": "新しいバージョンが利用可能です",
        "update_not_available": "最新版を使用しています",
        "update_failed": "アップデートに失敗しました",
        "about": "について",
        "version": "バージョン",
        "build": "ビルド",
        "changelog": "変更履歴",
        "open_source": "オープンソース",
        "licenses": "ライセンス",
    },
    "zh": {
        "crossfade": "淡入淡出",
        "crossfade_auto": "自动淡入淡出",
        "crossfade_description": "歌曲之间的平稳过渡",
        "crossfade_dj_mode": "DJ模式",
        "crossfading": "淡入淡出进行中",
        "sleep_timer": "睡眠计时器",
        "sleep_timer_description": "指定时间后停止音乐",
        "sleep_timer_minutes": "分钟",
        "remaining_time": "剩余时间",
        "auto_backup": "自动备份",
        "auto_backup_description": "定期备份音乐库",
        "backup_frequency": "备份频率",
        "keep_backups": "保留备份",
        "keep_backups_format": "最新{0}个",
        "last_backup": "最后备份",
        "last_backup_time": "运行于{0}",
        "backup_failed": "备份失败",
        "restore_backup": "还原备份",
        "restore_backup_description": "从以前的备份恢复数据",
        "select_backup": "选择要还原的备份",
        "restore": "还原",
        "backup_restored": "已还原备份",
        "upvote": "赞成",
        "downvote": "反对",
        "vote_for_lyrics": "投票选择歌词",
        "vote_submitted": "感谢您的投票！",
        "rate_lyrics": "评分歌词",
        "select_lyrics": "选择歌词",
        "discord_integration": "Discord集成",
        "enable_rich_presence": "启用Rich Presence",
        "discord_connect": "连接到Discord",
        "discord_disconnect": "从Discord断开连接",
        "connected_to_discord": "已连接到Discord",
        "disconnected_from_discord": "已从Discord断开连接",
        "daily": "每天",
        "weekly": "每周",
        "monthly": "每月",
        "last_7_days": "最后7天",
        "last_30_days": "最后30天",
        "last_90_days": "最后90天",
        "export_playlist": "导出播放列表",
        "import_playlist": "导入播放列表",
        "playlist_exported": "已导出播放列表",
        "playlist_imported": "已导入播放列表",
        "lyrics_downloaded": "已下载歌词",
        "lyrics_not_found": "未找到歌词",
        "queue_clear": "清除队列",
        "queue_cleared": "已清除队列",
        "queue_shuffle": "随机播放队列",
        "queue_repeat": "重复队列",
        "queue_repeat_one": "重复一首",
        "sort_by_name": "按名称排序",
        "sort_by_date": "按日期排序",
        "sort_by_artist": "按艺术家排序",
        "sort_by_album": "按专辑排序",
        "filter_all": "全部",
        "filter_favorite": "收藏夹",
        "filter_recently_played": "最近播放",
        "filter_most_played": "最常播放",
        "lyrics_sync": "同步歌词",
        "lyrics_sync_description": "根据播放的歌曲显示歌词",
        "enable_lyrics_sync": "启用歌词同步",
        "disable_lyrics_sync": "禁用歌词同步",
        "lyrics_sync_enabled": "歌词同步已启用",
        "lyrics_sync_disabled": "歌词同步已禁用",
        "delete_cache": "删除缓存",
        "delete_cache_description": "清除下载的数据",
        "cache_deleted": "已删除缓存",
        "check_update": "检查更新",
        "update_available": "有新版本可用",
        "update_not_available": "您正在使用最新版本",
        "update_failed": "更新失败",
        "about": "关于",
        "version": "版本",
        "build": "构建",
        "changelog": "更新日志",
        "open_source": "开源",
        "licenses": "许可证",
    },
    "in": {
        "crossfade": "Crossfade",
        "crossfade_auto": "Crossfade Otomatis",
        "crossfade_description": "Transisi mulus antara lagu",
        "crossfade_dj_mode": "Mode DJ",
        "crossfading": "Crossfade Berjalan",
        "sleep_timer": "Timer Tidur",
        "sleep_timer_description": "Hentikan musik setelah waktu tertentu",
        "sleep_timer_minutes": "menit",
        "remaining_time": "Waktu Tersisa",
        "auto_backup": "Cadangan Otomatis",
        "auto_backup_description": "Cadangkan perpustakaan secara berkala",
        "backup_frequency": "Frekuensi Cadangan",
        "keep_backups": "Simpan Cadangan",
        "keep_backups_format": "{0} terbaru",
        "last_backup": "Cadangan Terakhir",
        "last_backup_time": "Dijalankan pada {0}",
        "backup_failed": "Cadangan Gagal",
        "restore_backup": "Pulihkan Cadangan",
        "restore_backup_description": "Pulihkan data dari cadangan sebelumnya",
        "select_backup": "Pilih cadangan untuk dipulihkan",
        "restore": "Pulihkan",
        "backup_restored": "Cadangan dipulihkan",
        "upvote": "Sukai",
        "downvote": "Tidak Sukai",
        "vote_for_lyrics": "Pilih Lirik",
        "vote_submitted": "Terima kasih telah memilih!",
        "rate_lyrics": "Nilai Lirik",
        "select_lyrics": "Pilih Lirik",
        "discord_integration": "Integrasi Discord",
        "enable_rich_presence": "Aktifkan Rich Presence",
        "discord_connect": "Hubungkan ke Discord",
        "discord_disconnect": "Putuskan dari Discord",
        "connected_to_discord": "Terhubung ke Discord",
        "disconnected_from_discord": "Terputus dari Discord",
        "daily": "Harian",
        "weekly": "Mingguan",
        "monthly": "Bulanan",
        "last_7_days": "7 Hari Terakhir",
        "last_30_days": "30 Hari Terakhir",
        "last_90_days": "90 Hari Terakhir",
        "export_playlist": "Ekspor Daftar Putar",
        "import_playlist": "Impor Daftar Putar",
        "playlist_exported": "Daftar putar diekspor",
        "playlist_imported": "Daftar putar diimpor",
        "lyrics_downloaded": "Lirik diunduh",
        "lyrics_not_found": "Lirik tidak ditemukan",
        "queue_clear": "Kosongkan Antrian",
        "queue_cleared": "Antrian dikosongkan",
        "queue_shuffle": "Acak Antrian",
        "queue_repeat": "Ulangi Antrian",
        "queue_repeat_one": "Ulangi Satu",
        "sort_by_name": "Sortir Berdasarkan Nama",
        "sort_by_date": "Sortir Berdasarkan Tanggal",
        "sort_by_artist": "Sortir Berdasarkan Artis",
        "sort_by_album": "Sortir Berdasarkan Album",
        "filter_all": "Semua",
        "filter_favorite": "Favorit",
        "filter_recently_played": "Diputar Baru-baru Ini",
        "filter_most_played": "Paling Sering Diputar",
        "lyrics_sync": "Sinkronkan Lirik",
        "lyrics_sync_description": "Tampilkan lirik sesuai dengan lagu yang diputar",
        "enable_lyrics_sync": "Aktifkan Sinkronisasi Lirik",
        "disable_lyrics_sync": "Nonaktifkan Sinkronisasi Lirik",
        "lyrics_sync_enabled": "Sinkronisasi Lirik Diaktifkan",
        "lyrics_sync_disabled": "Sinkronisasi Lirik Dinonaktifkan",
        "delete_cache": "Hapus Cache",
        "delete_cache_description": "Bersihkan data yang diunduh",
        "cache_deleted": "Cache dihapus",
        "check_update": "Periksa Pembaruan",
        "update_available": "Versi baru tersedia",
        "update_not_available": "Anda menggunakan versi terbaru",
        "update_failed": "Pembaruan gagal",
        "about": "Tentang",
        "version": "Versi",
        "build": "Build",
        "changelog": "Catatan Perubahan",
        "open_source": "Sumber Terbuka",
        "licenses": "Lisensi",
    },
    "iw": {
        "crossfade": "התדלקות",
        "crossfade_auto": "התדלקות אוטומטית",
        "crossfade_description": "מעבר חלק בין שירים",
        "crossfade_dj_mode": "מצב DJ",
        "crossfading": "התדלקות בתהליך",
        "sleep_timer": "טיימר שינה",
        "sleep_timer_description": "עצור את הנגינה לאחר פרק זמן",
        "sleep_timer_minutes": "דקות",
        "remaining_time": "זמן שנותר",
        "auto_backup": "גיבוי אוטומטי",
        "auto_backup_description": "גבה את הספרייה שלך באופן קבוע",
        "backup_frequency": "תדירות גיבוי",
        "keep_backups": "שמור גיבויים",
        "keep_backups_format": "{0} האחרונים",
        "last_backup": "גיבוי אחרון",
        "last_backup_time": "הורץ בתאריך {0}",
        "backup_failed": "הגיבוי נכשל",
        "restore_backup": "שחזר גיבוי",
        "restore_backup_description": "שחזר את הנתונים מגיבוי קודם",
        "select_backup": "בחר גיבוי לשחזור",
        "restore": "שחזר",
        "backup_restored": "הגיבוי שוחזר",
        "upvote": "בחיוב",
        "downvote": "בשלילה",
        "vote_for_lyrics": "בחר בטקסט",
        "vote_submitted": "תודה על ההצבעה שלך!",
        "rate_lyrics": "דרג טקסט",
        "select_lyrics": "בחר בטקסט",
        "discord_integration": "אינטגרציה של Discord",
        "enable_rich_presence": "הפוך Rich Presence",
        "discord_connect": "התחבר ל-Discord",
        "discord_disconnect": "התנתק מ-Discord",
        "connected_to_discord": "מחובר ל-Discord",
        "disconnected_from_discord": "מנותק מ-Discord",
        "daily": "יומי",
        "weekly": "שבועי",
        "monthly": "חודשי",
        "last_7_days": "7 הימים האחרונים",
        "last_30_days": "30 הימים האחרונים",
        "last_90_days": "90 הימים האחרונים",
        "export_playlist": "ייצוא רשימת השמעה",
        "import_playlist": "ייבא רשימת השמעה",
        "playlist_exported": "רשימת ההשמעה יוצאה",
        "playlist_imported": "רשימת ההשמעה יובאה",
        "lyrics_downloaded": "טקסט הורד",
        "lyrics_not_found": "טקסט לא נמצא",
        "queue_clear": "נקה תור",
        "queue_cleared": "התור נוקה",
        "queue_shuffle": "זעזע תור",
        "queue_repeat": "חזור על התור",
        "queue_repeat_one": "חזור על אחד",
        "sort_by_name": "מיין לפי שם",
        "sort_by_date": "מיין לפי תאריך",
        "sort_by_artist": "מיין לפי אמן",
        "sort_by_album": "מיין לפי אלבום",
        "filter_all": "הכל",
        "filter_favorite": "מועדפים",
        "filter_recently_played": "הושמע לאחרונה",
        "filter_most_played": "הושמע ביותר",
        "lyrics_sync": "סנכרן טקסט",
        "lyrics_sync_description": "הצג טקסט בהתאם לשיר המושמע",
        "enable_lyrics_sync": "הפוך סנכרון טקסט",
        "disable_lyrics_sync": "השבת סנכרון טקסט",
        "lyrics_sync_enabled": "סנכרון טקסט הופעל",
        "lyrics_sync_disabled": "סנכרון טקסט השתבת",
        "delete_cache": "מחק זיכרון מטמון",
        "delete_cache_description": "מחק נתונים שהורדו",
        "cache_deleted": "זיכרון מטמון נמחק",
        "check_update": "חפש עדכונים",
        "update_available": "גרסה חדשה זמינה",
        "update_not_available": "אתה משתמש בגרסה העדכנית ביותר",
        "update_failed": "העדכון נכשל",
        "about": "אודות",
        "version": "גרסה",
        "build": "בנייה",
        "changelog": "רשימת שינויים",
        "open_source": "קוד פתוח",
        "licenses": "רישיונות",
    },
    "az": {
        "crossfade": "Keçid",
        "crossfade_auto": "Avtomatik Keçid",
        "crossfade_description": "Mahnılar arasında hamar keçid",
        "crossfade_dj_mode": "DJ Rejimi",
        "crossfading": "Keçid Aktiv",
        "sleep_timer": "Yuxu Taymeeri",
        "sleep_timer_description": "Müəyyən vaxt sonra musiqini dayandır",
        "sleep_timer_minutes": "dəqiqə",
        "remaining_time": "Qalan Vaxt",
        "auto_backup": "Avtomatik Ehtiyat",
        "auto_backup_description": "Mütəmadi olaraq kitabxananı ehtiyat götür",
        "backup_frequency": "Ehtiyat Tezliyi",
        "keep_backups": "Ehtiyatları Saxla",
        "keep_backups_format": "Son {0}",
        "last_backup": "Son Ehtiyat",
        "last_backup_time": "{0} də çalışdırıldı",
        "backup_failed": "Ehtiyat Uğursuz",
        "restore_backup": "Ehtiyatı Bərpa Et",
        "restore_backup_description": "Əvvəlki ehtiyatdan məlumatları bərpa et",
        "select_backup": "Bərpa etmək üçün ehtiyat seç",
        "restore": "Bərpa Et",
        "backup_restored": "Ehtiyat Bərpa Edildi",
        "upvote": "Bəyən",
        "downvote": "Bəyənmə",
        "vote_for_lyrics": "Sözlərə Səs Ver",
        "vote_submitted": "Səsiniz üçün təşəkkür edirik!",
        "rate_lyrics": "Sözləri Qiymətlə",
        "select_lyrics": "Sözləri Seç",
        "discord_integration": "Discord İntegrasiyası",
        "enable_rich_presence": "Rich Presence-i Aktiv Et",
        "discord_connect": "Discord-a Qoşul",
        "discord_disconnect": "Discord-dan Kəs",
        "connected_to_discord": "Discord-a Qoşuldu",
        "disconnected_from_discord": "Discord-dan Kəsildi",
        "daily": "Gündəlik",
        "weekly": "Həftəlik",
        "monthly": "Aylıq",
        "last_7_days": "Son 7 Gün",
        "last_30_days": "Son 30 Gün",
        "last_90_days": "Son 90 Gün",
        "export_playlist": "Pleylisti İxrac Et",
        "import_playlist": "Playisti İdxal Et",
        "playlist_exported": "Pleylisti İxrac Edildi",
        "playlist_imported": "Pleylisti İdxal Edildi",
        "lyrics_downloaded": "Sözlər Yükləndi",
        "lyrics_not_found": "Sözlər Tapılmadı",
        "queue_clear": "Sıraini Boşalt",
        "queue_cleared": "Sıra Boşaldı",
        "queue_shuffle": "Sıraini Karış",
        "queue_repeat": "Sıraı Təkrar Et",
        "queue_repeat_one": "Birini Təkrar Et",
        "sort_by_name": "Ada Görə Sırala",
        "sort_by_date": "Tarixə Görə Sırala",
        "sort_by_artist": "İcraçıya Görə Sırala",
        "sort_by_album": "Albuma Görə Sırala",
        "filter_all": "Hamısı",
        "filter_favorite": "Sevimli",
        "filter_recently_played": "Son Zamanlar Çalınan",
        "filter_most_played": "Ən Çox Çalınan",
        "lyrics_sync": "Sözləri Sinxronlaş",
        "lyrics_sync_description": "Çalınan mahnıya uyğun sözləri göstər",
        "enable_lyrics_sync": "Sözlərin Sinxronlaşmasını Aktiv Et",
        "disable_lyrics_sync": "Sözlərin Sinxronlaşmasını Söndür",
        "lyrics_sync_enabled": "Sözlərin Sinxronlaşması Aktiv",
        "lyrics_sync_disabled": "Sözlərin Sinxronlaşması Söndürülüb",
        "delete_cache": "Keşi Sil",
        "delete_cache_description": "Endirilmiş Məlumatı Təmizlə",
        "cache_deleted": "Keş Silindi",
        "check_update": "Yeniləmələri Yoxla",
        "update_available": "Yeni Versiya Mövcuddur",
        "update_not_available": "Siz Ən Yeni Versiyadan İstifadə Edirsiniz",
        "update_failed": "Yenilənmə Uğursuz",
        "about": "Haqqında",
        "version": "Versiya",
        "build": "Qurma",
        "changelog": "Dəyişikliklər Siyahısı",
        "open_source": "Açıq Mənbə",
        "licenses": "Lisenziyalar",
    },
    "bg": {
        "crossfade": "Кроссфейд",
        "crossfade_auto": "Автоматично кроссфейдване",
        "crossfade_description": "Плавен преход между парчета",
        "crossfade_dj_mode": "DJ режим",
        "crossfading": "Кроссфейдване в ход",
        "sleep_timer": "Таймер за сън",
        "sleep_timer_description": "Спри музиката след определено време",
        "sleep_timer_minutes": "минути",
        "remaining_time": "Оставащо време",
        "auto_backup": "Автоматично резервно копие",
        "auto_backup_description": "Редовно резервирай своята библиотека",
        "backup_frequency": "Честота на резервното копие",
        "keep_backups": "Запази резервни копия",
        "keep_backups_format": "Последние {0}",
        "last_backup": "Последното резервно копие",
        "last_backup_time": "Изпълнено на {0}",
        "backup_failed": "Резервното копие неуспешно",
        "restore_backup": "Възстанови резервно копие",
        "restore_backup_description": "Възстанови данни от предишно резервно копие",
        "select_backup": "Избери резервно копие за възстановяване",
        "restore": "Възстанови",
        "backup_restored": "Резервното копие възстановено",
        "upvote": "Нравиш ми",
        "downvote": "Не харесвам",
        "vote_for_lyrics": "Гласувай за текст",
        "vote_submitted": "Благодарим за вашия глас!",
        "rate_lyrics": "Оцени текста",
        "select_lyrics": "Избери текст",
        "discord_integration": "Discord интеграция",
        "enable_rich_presence": "Активирай Rich Presence",
        "discord_connect": "Свързване с Discord",
        "discord_disconnect": "Разкачване от Discord",
        "connected_to_discord": "Свързан с Discord",
        "disconnected_from_discord": "Разкачен от Discord",
        "daily": "Ежедневно",
        "weekly": "Седмично",
        "monthly": "Месечно",
        "last_7_days": "Последните 7 дни",
        "last_30_days": "Последните 30 дни",
        "last_90_days": "Последните 90 дни",
        "export_playlist": "Експортирай плейлиста",
        "import_playlist": "Импортирай плейлиста",
        "playlist_exported": "Плейлистът експортиран",
        "playlist_imported": "Плейлистът импортиран",
        "lyrics_downloaded": "Текстът изтеглен",
        "lyrics_not_found": "Текстът не намерен",
        "queue_clear": "Изчисти опашката",
        "queue_cleared": "Опашката изчистена",
        "queue_shuffle": "Разбъркай опашката",
        "queue_repeat": "Повтори опашката",
        "queue_repeat_one": "Повтори един",
        "sort_by_name": "Сортирай по име",
        "sort_by_date": "Сортирай по дата",
        "sort_by_artist": "Сортирай по артист",
        "sort_by_album": "Сортирай по албум",
        "filter_all": "Всички",
        "filter_favorite": "Любими",
        "filter_recently_played": "Наскоро пусната",
        "filter_most_played": "Най-често пусната",
        "lyrics_sync": "Синхронизирай текста",
        "lyrics_sync_description": "Показвай текста според възпроизводимата песен",
        "enable_lyrics_sync": "Активирай синхронизиране на текста",
        "disable_lyrics_sync": "Деактивирай синхронизиране на текста",
        "lyrics_sync_enabled": "Синхронизиране на текста активиран",
        "lyrics_sync_disabled": "Синхронизиране на текста деактивирано",
        "delete_cache": "Изтрий кеша",
        "delete_cache_description": "Изчисти изтеглените данни",
        "cache_deleted": "Кешът изтрит",
        "check_update": "Проверка за актуализации",
        "update_available": "Налична е нова версия",
        "update_not_available": "Използвате последната версия",
        "update_failed": "Актуализирането неуспешно",
        "about": "За",
        "version": "Версия",
        "build": "Сглобяване",
        "changelog": "История на промените",
        "open_source": "Отворен код",
        "licenses": "Лицензи",
    },
}

# 6 dil daha (CA, FA, FI, HI, NL, PL, TH, UK, VI, AR)
# Bu dilleri başka scriptte yapacağız

for lang_code, trans_dict in translations.items():
    lang_dir = os.path.join(base_path, f"values-{lang_code}")
    strings_file = os.path.join(lang_dir, "strings.xml")
    
    if not os.path.exists(strings_file):
        print(f"SKIP {lang_code}: Dosya bulunamadı")
        continue
    
    # Mevcut XML'i oku
    tree = ET.parse(strings_file)
    root = tree.getroot()
    
    # Var olan key'leri bul
    existing_keys = set()
    for string_elem in root.findall("string"):
        key = string_elem.get("name")
        if key:
            existing_keys.add(key)
    
    # Eksik çevirileri ekle
    added = 0
    for key, value in trans_dict.items():
        if key not in existing_keys:
            new_elem = ET.Element("string")
            new_elem.set("name", key)
            new_elem.text = value
            root.append(new_elem)
            added += 1
    
    # XML'i kaydet
    tree.write(strings_file, encoding="utf-8", xml_declaration=True)
    
    final_count = len(root.findall("string"))
    print(f"✓ {lang_code}: +{added} → {final_count} toplam çeviri")

print("\n✅ Tamamlandı!")
