#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import xml.etree.ElementTree as ET
from pathlib import Path

# Missing strings for ALL remaining languages
# These include ALL 86 missing strings plus any other missing ones

REMAINING_LANGS = {
    "hi": {  # Hindi - add all 86
        "auto_backup": "स्वचालित बैकअप",
        "auto_backup_description": "अपने डेटा को स्वचालित रूप से डाउनलोड/SimpMusic फ़ोल्डर में बैकअप करें",
        "auto_backup_failed": "स्वचालित बैकअप विफल",
        "auto_backup_success": "स्वचालित बैकअप सफलतापूर्वक पूर्ण",
        "backup_frequency": "बैकअप आवृत्ति",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "मिनी प्लेयर बंद करें",
        "combine_local_and_youtube_liked_songs": "लॉगिन के दौरान YouTube पसंद से पसंदीदा को बदलें",
        "combine_local_and_youtube_liked_songs_description": "केवल YouTube पसंद का उपयोग करें (ऑफ़लाइन गीत पसंद समर्थन नहीं)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "क्रॉसफेड (बीटा)",
        "crossfade_auto": "स्वचालित",
        "crossfade_auto_description": "BPM के आधार पर अवधि की स्वचालित गणना करें (320kbps स्ट्रीम और BPM डेटा की आवश्यकता)",
        "crossfade_description": "वर्तमान ट्रैक को फीका करते हुए अगले को फीका करके गीतों के बीच चिकनी संक्रमण करें।",
        "crossfade_dj_mode": "DJ-शैली संक्रमण",
        "crossfade_dj_mode_description": "क्रॉसफेड के दौरान कम-पास और उच्च-पास फिल्टर स्वीप लागू करें",
        "crossfading": "क्रॉसफेड चल रहा है",
        "daily": "दैनिक",
        "date_range": "तारीख श्रेणी",
        "desktop_player": "डेस्कटॉप प्लेयर",
        "desktop_webview_description": "Compose Multiplatform की सीमाओं के कारण, मैं डेस्कटॉप पर WebView लागू नहीं कर सकता।",
        "discord_integration": "डिस्कॉर्ड एकीकरण",
        "downvote": "असहमति",
        "enable_liquid_glass_effect_description": "कुछ स्थितियों में iOS के तरल कांच प्रभाव को सक्षम करें (Android 13+)",
        "enable_rich_presence": "Rich Presence सक्षम करें",
        "intro_login_to_discord": "Discord Rich Presence सक्षम करने के लिए लॉगिन करें",
        "keep_backups": "बैकअप रखें",
        "keep_backups_format": "अंतिम %1$s बैकअप रखें",
        "keep_service_alive": "सेवा को सक्रिय रखें",
        "keep_service_alive_description": "संगीत प्लेयर सेवा को सक्रिय रखें सिस्टम द्वारा बंद होने से बचने के लिए",
        "keep_your_youtube_playlist_offline": "YouTube प्लेलिस्ट को ऑफ़लाइन दिखाएं",
        "keep_your_youtube_playlist_offline_description": "अपनी YT प्लेलिस्ट को स्थानीय रूप से सहेजें और ऑफ़लाइन दिखाएं",
        "key": "कुंजी",
        "last_30_days": "पिछले 30 दिन",
        "last_7_days": "पिछले 7 दिन",
        "last_90_days": "पिछले 90 दिन",
        "last_backup": "अंतिम बैकअप",
        "local_tracking_description": "अपना सुनने का इतिहास स्थानीय डेटाबेस में लॉग करें",
        "local_tracking_title": "स्थानीय सुनने का इतिहास ट्रैकिंग",
        "log_in_to_discord": "Discord में लॉगिन करें",
        "lower_plays": "बजता है",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "BetterLyrics द्वारा प्रदान किए गए लिरिक्स",
        "monthly": "मासिक",
        "never": "कभी नहीं",
        "no_charts_found": "कोई चार्ट नहीं मिला",
        "no_data_analytics": "विश्लेषण देखने के लिए कुछ संगीत बजाएं",
        "notification_channel_name": "SimpMusic प्लेबैक सूचना",
        "open_app": "SimpMusic खोलें",
        "open_blog_post": "ब्लॉग पोस्ट खोलें",
        "open_miniplayer": "मिनी प्लेयर खोलें",
        "openai_api_compatible": "कस्टम OpenAI संगत",
        "podcasts": "पॉडकास्ट",
        "prefer_320kbps_stream": "320kbps स्ट्रीम को प्राथमिकता दें",
        "prefer_320kbps_stream_description": "इंटरनेट पर उपलब्ध होने पर 320kbps ऑडियो स्ट्रीम को स्वचालित रूप से खोजें",
        "proxy_password": "प्रॉक्सी पासवर्ड",
        "proxy_password_message": "कृपया अपना प्रॉक्सी पासवर्ड दर्ज करें (वैकल्पिक)",
        "proxy_username": "प्रॉक्सी उपयोगकर्ता नाम",
        "proxy_username_message": "कृपया अपना प्रॉक्सी उपयोगकर्ता नाम दर्ज करें (वैकल्पिक)",
        "quit_app": "ऐप से बाहर निकलें",
        "rate_lyrics": "लिरिक्स रेट करें",
        "rate_translated_lyrics": "अनुवाद रेट करें",
        "rich_presence_info": "Discord प्रोफ़ाइल पर मीडिया सेशन जानकारी दिखाएं",
        "scale": "पैमाना",
        "search_for": "के लिए खोजें",
        "seconds": "सेकंड",
        "simpmusic_charts": "SimpMusic चार्ट",
        "sleep_timer_end_of_song": "नींद टाइमर - गीत का अंत",
        "songs_played": "बजाए गए गीत",
        "synced_playlist_cannot_change_order": "सिंक किए गए प्लेलिस्ट का क्रम नहीं बदल सकता",
        "this_year": "इस साल",
        "top_song": "शीर्ष गीत",
        "total_listened_time": "कुल सुने गए समय",
        "upvote": "सहमती",
        "version_format": "v%1$s",
        "vote_error": "जमा करने में विफल",
        "vote_for_lyrics": "लिरिक्स के लिए वोट करें",
        "vote_submitted": "इन लिरिक्स के लिए वोट देने के लिए धन्यवाद!",
        "weekly": "साप्ताहिक",
        "your_320kbps_url": "आपका 320kbps URL",
        "your_recently_played": "हाल ही में बजाया गया",
        "your_top_albums": "आपके शीर्ष एल्बम",
        "your_top_artists": "आपके शीर्ष कलाकार",
        "your_top_tracks": "आपके शीर्ष ट्रैक",
        "youtube_liked_music": "YouTube पसंद संगीत"
    },
    "in": {  # Indonesian
        "auto_backup": "Pencadangan otomatis",
        "auto_backup_description": "Secara otomatis cadangkan data Anda ke folder Unduhan/SimpMusic",
        "auto_backup_failed": "Pencadangan otomatis gagal",
        "auto_backup_success": "Pencadangan otomatis selesai dengan sukses",
        "backup_frequency": "Frekuensi pencadangan",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "Tutup pemain mini",
        "combine_local_and_youtube_liked_songs": "Ganti Favorit dengan YouTube Disukai saat login",
        "combine_local_and_youtube_liked_songs_description": "Gunakan hanya YouTube Disukai (tidak mendukung menyukai lagu saat offline)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "Perpaduan silang (BETA)",
        "crossfade_auto": "Otomatis",
        "crossfade_auto_description": "Hitung durasi secara otomatis berdasarkan BPM (memerlukan aliran 320kbps dengan data BPM)",
        "crossfade_description": "Buat transisi halus antar lagu dengan memudarkan trek saat ini sambil memudarkan trek berikutnya.",
        "crossfade_dj_mode": "Transisi Gaya DJ",
        "crossfade_dj_mode_description": "Terapkan sapuan filter lulus rendah dan lulus tinggi selama perpaduan silang",
        "crossfading": "Perpaduan silang sedang berlangsung",
        "daily": "Harian",
        "date_range": "Rentang tanggal",
        "desktop_player": "Pemain desktop",
        "desktop_webview_description": "Karena keterbatasan Compose Multiplatform, saya tidak dapat menerapkan WebView di desktop.",
        "discord_integration": "Integrasi Discord",
        "downvote": "Tidak menyukai",
        "enable_liquid_glass_effect_description": "Aktifkan efek kaca cair iOS di beberapa posisi (Android 13+)",
        "enable_rich_presence": "Aktifkan Rich Presence",
        "intro_login_to_discord": "Login untuk mengaktifkan Discord Rich Presence",
        "keep_backups": "Simpan pencadangan",
        "keep_backups_format": "Simpan %1$s pencadangan terakhir",
        "keep_service_alive": "Jaga layanan tetap aktif",
        "keep_service_alive_description": "Jaga layanan pemain musik tetap aktif untuk menghindari penghentian oleh sistem",
        "keep_your_youtube_playlist_offline": "Jaga daftar putar YouTube tetap offline",
        "keep_your_youtube_playlist_offline_description": "Simpan daftar putar YT Anda secara lokal dan tampilkan saat offline",
        "key": "Kunci",
        "last_30_days": "30 hari terakhir",
        "last_7_days": "7 hari terakhir",
        "last_90_days": "90 hari terakhir",
        "last_backup": "Pencadangan terakhir",
        "local_tracking_description": "Catat riwayat mendengarkan ke database lokal",
        "local_tracking_title": "Pelacakan riwayat mendengarkan lokal",
        "log_in_to_discord": "Login ke Discord",
        "lower_plays": "pemutaran",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "Lirik disediakan oleh BetterLyrics",
        "monthly": "Bulanan",
        "never": "Tidak pernah",
        "no_charts_found": "Tidak ada grafik yang ditemukan",
        "no_data_analytics": "Mainkan beberapa musik untuk melihat analitik",
        "notification_channel_name": "Pemberitahuan Pemutaran SimpMusic",
        "open_app": "Buka SimpMusic",
        "open_blog_post": "Buka posting blog",
        "open_miniplayer": "Buka pemain mini",
        "openai_api_compatible": "Kompatibel OpenAI Khusus",
        "podcasts": "Podcast",
        "prefer_320kbps_stream": "Lebih suka aliran 320kbps",
        "prefer_320kbps_stream_description": "Cari aliran audio 320kbps secara otomatis saat tersedia di internet",
        "proxy_password": "Kata sandi proxy",
        "proxy_password_message": "Silakan masukkan kata sandi proxy Anda (opsional)",
        "proxy_username": "Nama pengguna proxy",
        "proxy_username_message": "Silakan masukkan nama pengguna proxy Anda (opsional)",
        "quit_app": "Keluar dari aplikasi",
        "rate_lyrics": "Nilai lirik",
        "rate_translated_lyrics": "Nilai terjemahan",
        "rich_presence_info": "Tampilkan informasi sesi media di profil Discord Anda",
        "scale": "Skala",
        "search_for": "Cari",
        "seconds": "detik",
        "simpmusic_charts": "Bagan SimpMusic",
        "sleep_timer_end_of_song": "Penghitung waktu tidur - Akhir lagu",
        "songs_played": "Lagu diputar",
        "synced_playlist_cannot_change_order": "Urutan daftar putar yang disinkronkan tidak dapat diubah",
        "this_year": "Tahun ini",
        "top_song": "Lagu teratas",
        "total_listened_time": "Total waktu didengarkan",
        "upvote": "Menyukai",
        "version_format": "v%1$s",
        "vote_error": "Gagal mengirim",
        "vote_for_lyrics": "Suara untuk lirik",
        "vote_submitted": "Terima kasih telah memberikan suara untuk lirik ini!",
        "weekly": "Mingguan",
        "your_320kbps_url": "URL 320kbps Anda",
        "your_recently_played": "Diputar baru-baru ini",
        "your_top_albums": "Album teratas Anda",
        "your_top_artists": "Artis teratas Anda",
        "your_top_tracks": "Lagu teratas Anda",
        "youtube_liked_music": "Musik YouTube yang Anda Sukai"
    },
    "iw": {  # Hebrew - simplified
        "auto_backup": "גיבוי אוטומטי",
        "auto_backup_description": "גיבוי נתונים שלך באופן אוטומטי לתיקיית הורדות/SimpMusic",
        "auto_backup_failed": "גיבוי אוטומטי נכשל",
        "auto_backup_success": "גיבוי אוטומטי הושלם בהצלחה",
        "backup_frequency": "תדירות גיבוי",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "סגור נגן מיני",
        "combine_local_and_youtube_liked_songs": "החלף מועדף ב-YouTube מועדף בעת התחברות",
        "combine_local_and_youtube_liked_songs_description": "השתמש רק ב-YouTube מועדף (לא תומך בהערכת שיר בעת הפעלת מצב לא מקוון)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "המתזה (בטא)",
        "crossfade_auto": "אוטומטי",
        "crossfade_auto_description": "חשב משך זמן אוטומטי על סמך BPM (דורש סטרם 320kbps עם נתוני BPM)",
        "crossfade_description": "בצע מעבר חלק בין שירים על ידי התחשבות ברצועה הנוכחית תוך פתיחת הבאה.",
        "crossfade_dj_mode": "מעבר בסגנון DJ",
        "crossfade_dj_mode_description": "החל סוודות מסנן עמוק וגבוה במהלך הממתזה",
        "crossfading": "מתזה מתחולל",
        "daily": "יומי",
        "date_range": "טווח תאריכים",
        "desktop_player": "נגן שולחן עבודה",
        "desktop_webview_description": "בגלל מגבלות Compose Multiplatform, אני לא יכול ליישם WebView בשולחן עבודה.",
        "discord_integration": "שילוב Discord",
        "downvote": "לא אוהב",
        "enable_liquid_glass_effect_description": "הפוך אפקט זכוכית נוזלית של iOS במצבים מסוימים (Android 13+)",
        "enable_rich_presence": "אפשר Rich Presence",
        "intro_login_to_discord": "התחבר להפעלת Discord Rich Presence",
        "keep_backups": "שמור גיבויים",
        "keep_backups_format": "שמור גיבויים %1$s אחרונים",
        "keep_service_alive": "שמור על השירות בחיים",
        "keep_service_alive_description": "שמור על שירות נגן המוזיקה בחיים כדי להימנע מסיום על ידי המערכת",
        "keep_your_youtube_playlist_offline": "שמור על רשימת ההשמעה של YouTube בחו",
        "keep_your_youtube_playlist_offline_description": "שמור את רשימת ההשמעה של YT שלך באופן מקומי וחשוף אותה כשאתה מנותק",
        "key": "מפתח",
        "last_30_days": "30 הימים האחרונים",
        "last_7_days": "7 הימים האחרונים",
        "last_90_days": "90 הימים האחרונים",
        "last_backup": "גיבוי אחרון",
        "local_tracking_description": "תיעד את היסטוריית ההאזנה שלך למסד הנתונים המקומי",
        "local_tracking_title": "מעקב היסטוריית האזנה מקומי",
        "log_in_to_discord": "התחבר ל-Discord",
        "lower_plays": "נגינות",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "מילים מסופקות על ידי BetterLyrics",
        "monthly": "חודשי",
        "never": "לעולם לא",
        "no_charts_found": "לא נמצאו תרשימים",
        "no_data_analytics": "נגן קצת מוזיקה כדי לראות אנליטיקה",
        "notification_channel_name": "הודעת ההשמעה של SimpMusic",
        "open_app": "פתח SimpMusic",
        "open_blog_post": "פתח פוסט בבלוג",
        "open_miniplayer": "פתח נגן מיני",
        "openai_api_compatible": "תואם OpenAI מותאם",
        "podcasts": "פודקסטים",
        "prefer_320kbps_stream": "עדיף סטרם 320kbps",
        "prefer_320kbps_stream_description": "חפש בעצמך סטרם אודיו 320kbps כשהוא זמין באינטרנט",
        "proxy_password": "סיסמת proxy",
        "proxy_password_message": "אנא הזן את סיסמת proxy שלך (אופציונלי)",
        "proxy_username": "שם משתמש proxy",
        "proxy_username_message": "אנא הזן את שם המשתמש proxy שלך (אופציונלי)",
        "quit_app": "יצא מהאפליקציה",
        "rate_lyrics": "דרג מילים",
        "rate_translated_lyrics": "דרג תרגום",
        "rich_presence_info": "הצג מידע על הפעת מדיה בפרופיל Discord שלך",
        "scale": "סולם",
        "search_for": "חפש",
        "seconds": "שניות",
        "simpmusic_charts": "תרשימי SimpMusic",
        "sleep_timer_end_of_song": "טיימר שינה - סוף שיר",
        "songs_played": "שירים ששודרו",
        "synced_playlist_cannot_change_order": "לא ניתן לשנות סדר רשימת ההשמעה המסונכרנת",
        "this_year": "השנה הזאת",
        "top_song": "שיר המובילה",
        "total_listened_time": "סך הזמן שהאזנו",
        "upvote": "אהוב",
        "version_format": "v%1$s",
        "vote_error": "שליחה נכשלה",
        "vote_for_lyrics": "הצביע למילים",
        "vote_submitted": "תודה על הצבעה למילים אלה!",
        "weekly": "שבועי",
        "your_320kbps_url": "כתובת ה-URL של 320kbps שלך",
        "your_recently_played": "שודר לאחרונה",
        "your_top_albums": "האלבומים המובילים שלך",
        "your_top_artists": "אמנים המובילים שלך",
        "your_top_tracks": "הרצועות המובילות שלך",
        "youtube_liked_music": "מוזיקה שאתה אוהב ב-YouTube"
    }
}

def add_missing_strings(filepath, lang_translations):
    """Add missing strings to XML file"""
    try:
        tree = ET.parse(filepath)
        root = tree.getroot()
        
        existing_keys = set()
        for elem in root.findall('string'):
            existing_keys.add(elem.get('name'))
        
        added = 0
        for key, value in lang_translations.items():
            if key not in existing_keys:
                string_elem = ET.SubElement(root, 'string')
                string_elem.set('name', key)
                string_elem.text = value
                added += 1
        
        tree.write(filepath, encoding='utf-8', xml_declaration=True)
        return added
    except Exception as e:
        print(f"Error: {e}")
        return 0

base_path = Path("C:/Users/kIrik/desktop/py/simpmusic/SimpMusic/composeApp/src/commonMain/composeResources")

print("Adding missing translations to Hindi, Indonesian, Hebrew...\n")

for lang_code, translations in REMAINING_LANGS.items():
    xml_file = base_path / f"values-{lang_code}" / "strings.xml"
    if xml_file.exists():
        added = add_missing_strings(xml_file, translations)
        print(f"✓ {lang_code}: Added {added} strings")
    else:
        print(f"✗ {lang_code}: File not found")

print("\n✓ Complete!")
