#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import xml.etree.ElementTree as ET
from pathlib import Path

# Remaining language translations (22 more languages)
TRANSLATIONS_PART2 = {
    "es": {
        "auto_backup": "Copia de seguridad automática",
        "auto_backup_description": "Realiza automáticamente una copia de seguridad de tus datos en la carpeta Descargas/SimpMusic",
        "auto_backup_failed": "Error en la copia de seguridad automática",
        "auto_backup_success": "Copia de seguridad automática completada con éxito",
        "backup_frequency": "Frecuencia de copia de seguridad",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "Cerrar mini reproductor",
        "combine_local_and_youtube_liked_songs": "Reemplazar favoritos por gustos de YouTube al iniciar sesión",
        "combine_local_and_youtube_liked_songs_description": "Utilizar solo los gustos de YouTube (no admite gustar canciones sin conexión)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "Mezcla suave (BETA)",
        "crossfade_auto": "Automático",
        "crossfade_auto_description": "Calcula automáticamente la duración según BPM (requiere transmisión de 320 kbps con datos de BPM)",
        "crossfade_description": "Realiza una transición suave entre canciones desvaneciendo la pista actual mientras se abre la siguiente.",
        "crossfade_dj_mode": "Transición al estilo DJ",
        "crossfade_dj_mode_description": "Aplica barridos de filtros paso bajo y paso alto durante la mezcla suave para una transición más suave al estilo DJ",
        "crossfading": "Mezcla suave en progreso",
        "daily": "Diario",
        "date_range": "Rango de fechas",
        "desktop_player": "Reproductor de escritorio",
        "desktop_webview_description": "Debido a las limitaciones de Compose Multiplatform, no puedo implementar WebView en el escritorio.",
        "discord_integration": "Integración de Discord",
        "downvote": "No me gusta",
        "enable_liquid_glass_effect_description": "Habilita el efecto de vidrio líquido de iOS en algunas posiciones (Android 13+)",
        "enable_rich_presence": "Habilitar presencia enriquecida",
        "intro_login_to_discord": "Inicie sesión para habilitar Discord Rich Presence",
        "keep_backups": "Mantener copias de seguridad",
        "keep_backups_format": "Mantener las últimas %1$s copias de seguridad",
        "keep_service_alive": "Mantener el servicio activo",
        "keep_service_alive_description": "Mantén el servicio del reproductor de música activo para evitar que el sistema lo cierre",
        "keep_your_youtube_playlist_offline": "Mantener la lista de reproducción de YouTube sin conexión",
        "keep_your_youtube_playlist_offline_description": "Guarda tu lista de reproducción de YT localmente y muéstrala sin conexión",
        "key": "Clave",
        "last_30_days": "Últimos 30 días",
        "last_7_days": "Últimos 7 días",
        "last_90_days": "Últimos 90 días",
        "last_backup": "Última copia de seguridad",
        "local_tracking_description": "Registra tu historial de escucha en la base de datos local",
        "local_tracking_title": "Seguimiento del historial de escucha local",
        "log_in_to_discord": "Inicie sesión en Discord",
        "lower_plays": "reproducciones",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "Letras proporcionadas por BetterLyrics",
        "monthly": "Mensual",
        "never": "Nunca",
        "no_charts_found": "No se encontraron gráficos",
        "no_data_analytics": "Toca algo de música para ver análisis",
        "notification_channel_name": "Notificación de reproducción de SimpMusic",
        "open_app": "Abrir SimpMusic",
        "open_blog_post": "Abrir entrada de blog",
        "open_miniplayer": "Abrir mini reproductor",
        "openai_api_compatible": "Compatible personalizado con OpenAI",
        "podcasts": "Podcasts",
        "prefer_320kbps_stream": "Preferir transmisión de 320 kbps",
        "prefer_320kbps_stream_description": "Busca automáticamente transmisión de audio de 320 kbps cuando esté disponible en Internet",
        "proxy_password": "Contraseña del proxy",
        "proxy_password_message": "Ingrese su contraseña de proxy (opcional)",
        "proxy_username": "Nombre de usuario del proxy",
        "proxy_username_message": "Ingrese su nombre de usuario de proxy (opcional)",
        "quit_app": "Salir de la aplicación",
        "rate_lyrics": "Calificar letras",
        "rate_translated_lyrics": "Calificar traducción",
        "rich_presence_info": "Mostrar información de sesión multimedia en tu perfil de Discord",
        "scale": "Escala",
        "search_for": "Buscar",
        "seconds": "segundos",
        "simpmusic_charts": "Gráficos de SimpMusic",
        "sleep_timer_end_of_song": "Temporizador de sueño - Fin de canción",
        "songs_played": "Canciones reproducidas",
        "synced_playlist_cannot_change_order": "No se puede cambiar el orden de la lista de reproducción sincronizada",
        "this_year": "Este año",
        "top_song": "Canción principal",
        "total_listened_time": "Tiempo total escuchado",
        "upvote": "Me gusta",
        "version_format": "v%1$s",
        "vote_error": "Error al enviar",
        "vote_for_lyrics": "Votar por letras",
        "vote_submitted": "¡Gracias por votar estas letras!",
        "weekly": "Semanal",
        "your_320kbps_url": "Tu URL de 320 kbps",
        "your_recently_played": "Reproducido recientemente",
        "your_top_albums": "Tus álbumes principales",
        "your_top_artists": "Tus artistas principales",
        "your_top_tracks": "Tus canciones principales",
        "youtube_liked_music": "Música que te gusta de YouTube"
    },
    "it": {
        "auto_backup": "Backup automatico",
        "auto_backup_description": "Esegui automaticamente il backup dei tuoi dati nella cartella Download/SimpMusic",
        "auto_backup_failed": "Backup automatico non riuscito",
        "auto_backup_success": "Backup automatico completato con successo",
        "backup_frequency": "Frequenza di backup",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "Chiudi mini player",
        "combine_local_and_youtube_liked_songs": "Sostituisci preferiti con Mi piace di YouTube quando accedi",
        "combine_local_and_youtube_liked_songs_description": "Utilizza solo Mi piace di YouTube (non supporta l'aggiunta di Mi piace a una canzone offline)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "Dissolvenza incrociata (BETA)",
        "crossfade_auto": "Automatico",
        "crossfade_auto_description": "Calcola automaticamente la durata in base al BPM (richiede flusso 320 kbps con dati BPM)",
        "crossfade_description": "Effettua una transizione fluida tra le canzoni dissolvendo la traccia corrente mentre si apre la seguente.",
        "crossfade_dj_mode": "Transizione nello stile DJ",
        "crossfade_dj_mode_description": "Applica sweep di filtro passa-basso e passa-alto durante la dissolvenza incrociata per una transizione più fluida",
        "crossfading": "Dissolvenza incrociata in corso",
        "daily": "Giornaliero",
        "date_range": "Intervallo di date",
        "desktop_player": "Lettore desktop",
        "desktop_webview_description": "A causa delle limitazioni di Compose Multiplatform, non posso implementare WebView sul desktop.",
        "discord_integration": "Integrazione Discord",
        "downvote": "Non mi piace",
        "enable_liquid_glass_effect_description": "Abilita l'effetto vetro liquido di iOS in alcune posizioni (Android 13+)",
        "enable_rich_presence": "Abilita rich presence",
        "intro_login_to_discord": "Accedi per abilitare Discord Rich Presence",
        "keep_backups": "Mantieni backup",
        "keep_backups_format": "Mantieni gli ultimi %1$s backup",
        "keep_service_alive": "Mantieni il servizio attivo",
        "keep_service_alive_description": "Mantieni il servizio del lettore musicale attivo per evitare che venga terminato dal sistema",
        "keep_your_youtube_playlist_offline": "Mantieni la playlist di YouTube offline",
        "keep_your_youtube_playlist_offline_description": "Salva la tua playlist YT localmente e visualizzala offline",
        "key": "Chiave",
        "last_30_days": "Ultimi 30 giorni",
        "last_7_days": "Ultimi 7 giorni",
        "last_90_days": "Ultimi 90 giorni",
        "last_backup": "Ultimo backup",
        "local_tracking_description": "Registra la tua cronologia di ascolto nel database locale",
        "local_tracking_title": "Tracciamento locale della cronologia di ascolto",
        "log_in_to_discord": "Accedi a Discord",
        "lower_plays": "riproduzioni",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "Testi forniti da BetterLyrics",
        "monthly": "Mensile",
        "never": "Mai",
        "no_charts_found": "Nessun grafico trovato",
        "no_data_analytics": "Riproduci della musica per visualizzare le analisi",
        "notification_channel_name": "Notifica di riproduzione SimpMusic",
        "open_app": "Apri SimpMusic",
        "open_blog_post": "Apri articolo del blog",
        "open_miniplayer": "Apri mini player",
        "openai_api_compatible": "Personalizzato compatibile OpenAI",
        "podcasts": "Podcast",
        "prefer_320kbps_stream": "Preferisci flusso 320 kbps",
        "prefer_320kbps_stream_description": "Cerca automaticamente il flusso audio 320 kbps quando disponibile su Internet",
        "proxy_password": "Password proxy",
        "proxy_password_message": "Inserisci la tua password proxy (facoltativo)",
        "proxy_username": "Nome utente proxy",
        "proxy_username_message": "Inserisci il tuo nome utente proxy (facoltativo)",
        "quit_app": "Esci dall'app",
        "rate_lyrics": "Valuta i testi",
        "rate_translated_lyrics": "Valuta la traduzione",
        "rich_presence_info": "Mostra le informazioni della sessione multimediale nel tuo profilo Discord",
        "scale": "Scala",
        "search_for": "Cerca",
        "seconds": "secondi",
        "simpmusic_charts": "Grafici SimpMusic",
        "sleep_timer_end_of_song": "Timer di sospensione - Fine brano",
        "songs_played": "Canzoni riprodotte",
        "synced_playlist_cannot_change_order": "Non è possibile modificare l'ordine della playlist sincronizzata",
        "this_year": "Questo anno",
        "top_song": "Brano principale",
        "total_listened_time": "Tempo totale di ascolto",
        "upvote": "Mi piace",
        "version_format": "v%1$s",
        "vote_error": "Invio non riuscito",
        "vote_for_lyrics": "Vota i testi",
        "vote_submitted": "Grazie per aver votato questi testi!",
        "weekly": "Settimanale",
        "your_320kbps_url": "Il tuo URL 320 kbps",
        "your_recently_played": "Riprodotto di recente",
        "your_top_albums": "I tuoi album principali",
        "your_top_artists": "I tuoi artisti principali",
        "your_top_tracks": "I tuoi brani principali",
        "youtube_liked_music": "Musica che mi piace su YouTube"
    },
    "ru": {
        "auto_backup": "Автоматическое резервное копирование",
        "auto_backup_description": "Автоматически сохраняйте ваши данные в папку Загрузки/SimpMusic",
        "auto_backup_failed": "Автоматическое резервное копирование не удалось",
        "auto_backup_success": "Автоматическое резервное копирование успешно завершено",
        "backup_frequency": "Частота резервного копирования",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "Закрыть мини-плеер",
        "combine_local_and_youtube_liked_songs": "Заменить избранное на понравившиеся видео с YouTube при входе",
        "combine_local_and_youtube_liked_songs_description": "Использовать только понравившиеся видео с YouTube (не поддерживает отметку песни как понравившейся в автономном режиме)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "Плавный переход (БЕТА)",
        "crossfade_auto": "Автоматический",
        "crossfade_auto_description": "Автоматически рассчитывайте продолжительность на основе BPM (требуется поток 320 кбит/с с данными BPM)",
        "crossfade_description": "Плавный переход между песнями путем затухания текущей дорожки и включения следующей.",
        "crossfade_dj_mode": "DJ-переход",
        "crossfade_dj_mode_description": "Применяйте развертки фильтра нижних и верхних частот во время плавного перехода для более плавного DJ-подобного перехода",
        "crossfading": "Плавный переход выполняется",
        "daily": "Ежедневно",
        "date_range": "Диапазон дат",
        "desktop_player": "Настольный плеер",
        "desktop_webview_description": "Из-за ограничений Compose Multiplatform я не могу реализовать WebView на рабочем столе.",
        "discord_integration": "Интеграция Discord",
        "downvote": "Не нравится",
        "enable_liquid_glass_effect_description": "Включите эффект жидкого стекла iOS в некоторых положениях (Android 13+)",
        "enable_rich_presence": "Включить Rich Presence",
        "intro_login_to_discord": "Войдите, чтобы включить Discord Rich Presence",
        "keep_backups": "Хранить резервные копии",
        "keep_backups_format": "Хранить последние %1$s резервные копии",
        "keep_service_alive": "Держать сервис активным",
        "keep_service_alive_description": "Держите сервис музыкального проигрывателя активным, чтобы система его не завершила",
        "keep_your_youtube_playlist_offline": "Сохранять плейлист YouTube в автономном режиме",
        "keep_your_youtube_playlist_offline_description": "Сохраняйте плейлист YT локально и отображайте его в автономном режиме",
        "key": "Ключ",
        "last_30_days": "За последние 30 дней",
        "last_7_days": "За последние 7 дней",
        "last_90_days": "За последние 90 дней",
        "last_backup": "Последняя резервная копия",
        "local_tracking_description": "Записывайте историю прослушивания в локальную базу данных",
        "local_tracking_title": "Локальное отслеживание истории прослушивания",
        "log_in_to_discord": "Войти в Discord",
        "lower_plays": "воспроизведение",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "Текст песни предоставлен BetterLyrics",
        "monthly": "Ежемесячно",
        "never": "Никогда",
        "no_charts_found": "Диаграммы не найдены",
        "no_data_analytics": "Включите музыку для просмотра аналитики",
        "notification_channel_name": "Уведомление воспроизведения SimpMusic",
        "open_app": "Открыть SimpMusic",
        "open_blog_post": "Открыть сообщение в блоге",
        "open_miniplayer": "Открыть мини-плеер",
        "openai_api_compatible": "Пользовательский совместимый OpenAI",
        "podcasts": "Подкасты",
        "prefer_320kbps_stream": "Предпочитать поток 320 кбит/с",
        "prefer_320kbps_stream_description": "Автоматически ищите аудиопоток 320 кбит/с при наличии в Интернете",
        "proxy_password": "Пароль прокси",
        "proxy_password_message": "Пожалуйста, введите пароль прокси (необязательно)",
        "proxy_username": "Имя пользователя прокси",
        "proxy_username_message": "Пожалуйста, введите имя пользователя прокси (необязательно)",
        "quit_app": "Выйти из приложения",
        "rate_lyrics": "Оценить текст песни",
        "rate_translated_lyrics": "Оценить перевод",
        "rich_presence_info": "Показывать информацию о сеансе медиа в профиле Discord",
        "scale": "Масштаб",
        "search_for": "Поиск",
        "seconds": "секунды",
        "simpmusic_charts": "Графики SimpMusic",
        "sleep_timer_end_of_song": "Таймер сна - Конец песни",
        "songs_played": "Песен воспроизведено",
        "synced_playlist_cannot_change_order": "Невозможно изменить порядок синхронизированного плейлиста",
        "this_year": "В этом году",
        "top_song": "Лучшая песня",
        "total_listened_time": "Общее время прослушивания",
        "upvote": "Нравится",
        "version_format": "v%1$s",
        "vote_error": "Ошибка отправки",
        "vote_for_lyrics": "Голосование за текст песни",
        "vote_submitted": "Спасибо за голосование по этому тексту песни!",
        "weekly": "Еженедельно",
        "your_320kbps_url": "Ваш URL 320 кбит/с",
        "your_recently_played": "Недавно прослушивалось",
        "your_top_albums": "Ваши лучшие альбомы",
        "your_top_artists": "Ваши лучшие исполнители",
        "your_top_tracks": "Ваши лучшие песни",
        "youtube_liked_music": "Понравившаяся музыка с YouTube"
    },
    "pt": {
        "auto_backup": "Backup automático",
        "auto_backup_description": "Faça backup automaticamente de seus dados na pasta Downloads/SimpMusic",
        "auto_backup_failed": "Falha no backup automático",
        "auto_backup_success": "Backup automático concluído com sucesso",
        "backup_frequency": "Frequência de backup",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "Fechar minireprotor",
        "combine_local_and_youtube_liked_songs": "Substituir favoritos por vídeos marcados com gosto no YouTube ao fazer login",
        "combine_local_and_youtube_liked_songs_description": "Usar apenas músicas marcadas com gosto no YouTube (não suporta marcar música como favorita offline)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "Transição suave (BETA)",
        "crossfade_auto": "Automático",
        "crossfade_auto_description": "Calcule automaticamente a duração com base no BPM (requer stream de 320 kbps com dados de BPM)",
        "crossfade_description": "Faça uma transição suave entre as músicas atenuando a faixa atual enquanto abre a próxima.",
        "crossfade_dj_mode": "Transição ao estilo DJ",
        "crossfade_dj_mode_description": "Aplique varreduras de filtro passa-baixa e passa-alta durante transição suave para uma transição mais suave",
        "crossfading": "Transição suave em andamento",
        "daily": "Diariamente",
        "date_range": "Intervalo de datas",
        "desktop_player": "Reprodutor de desktop",
        "desktop_webview_description": "Devido às limitações do Compose Multiplatform, não posso implementar WebView no desktop.",
        "discord_integration": "Integração com Discord",
        "downvote": "Desgosto",
        "enable_liquid_glass_effect_description": "Ative o efeito de vidro líquido do iOS em algumas posições (Android 13+)",
        "enable_rich_presence": "Ativar Rich Presence",
        "intro_login_to_discord": "Faça login para ativar o Discord Rich Presence",
        "keep_backups": "Manter backups",
        "keep_backups_format": "Manter os últimos %1$s backups",
        "keep_service_alive": "Manter o serviço ativo",
        "keep_service_alive_description": "Mantenha o serviço do player de música ativo para evitar que seja encerrado pelo sistema",
        "keep_your_youtube_playlist_offline": "Manter playlist do YouTube offline",
        "keep_your_youtube_playlist_offline_description": "Salve sua playlist do YT localmente e exiba-a offline",
        "key": "Chave",
        "last_30_days": "Últimos 30 dias",
        "last_7_days": "Últimos 7 dias",
        "last_90_days": "Últimos 90 dias",
        "last_backup": "Último backup",
        "local_tracking_description": "Registre seu histórico de audição no banco de dados local",
        "local_tracking_title": "Rastreamento local do histórico de audição",
        "log_in_to_discord": "Faça login no Discord",
        "lower_plays": "reproduções",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "Letras fornecidas por BetterLyrics",
        "monthly": "Mensalmente",
        "never": "Nunca",
        "no_charts_found": "Nenhum gráfico encontrado",
        "no_data_analytics": "Toque uma música para ver a análise",
        "notification_channel_name": "Notificação de reprodução do SimpMusic",
        "open_app": "Abrir SimpMusic",
        "open_blog_post": "Abrir post do blog",
        "open_miniplayer": "Abrir minireprotor",
        "openai_api_compatible": "OpenAI compatível personalizado",
        "podcasts": "Podcasts",
        "prefer_320kbps_stream": "Preferir stream de 320 kbps",
        "prefer_320kbps_stream_description": "Procure automaticamente por stream de áudio de 320 kbps quando disponível na internet",
        "proxy_password": "Senha do proxy",
        "proxy_password_message": "Digite sua senha de proxy (opcional)",
        "proxy_username": "Nome de usuário do proxy",
        "proxy_username_message": "Digite seu nome de usuário do proxy (opcional)",
        "quit_app": "Sair do aplicativo",
        "rate_lyrics": "Avaliar letras",
        "rate_translated_lyrics": "Avaliar tradução",
        "rich_presence_info": "Mostrar informações de sessão de mídia em seu perfil do Discord",
        "scale": "Escala",
        "search_for": "Procurar",
        "seconds": "segundos",
        "simpmusic_charts": "Gráficos SimpMusic",
        "sleep_timer_end_of_song": "Temporizador de sono - Fim da música",
        "songs_played": "Músicas tocadas",
        "synced_playlist_cannot_change_order": "A ordem da playlist sincronizada não pode ser alterada",
        "this_year": "Este ano",
        "top_song": "Música principal",
        "total_listened_time": "Tempo total de audição",
        "upvote": "Gostar",
        "version_format": "v%1$s",
        "vote_error": "Falha ao enviar",
        "vote_for_lyrics": "Votar nas letras",
        "vote_submitted": "Obrigado por votar nesta letra!",
        "weekly": "Semanalmente",
        "your_320kbps_url": "Seu URL de 320 kbps",
        "your_recently_played": "Tocado recentemente",
        "your_top_albums": "Seus melhores álbuns",
        "your_top_artists": "Seus melhores artistas",
        "your_top_tracks": "Suas melhores músicas",
        "youtube_liked_music": "Música que você gostou do YouTube"
    },
    "ja": {
        "auto_backup": "自動バックアップ",
        "auto_backup_description": "データを自動的にダウンロード/SimpMusicフォルダにバックアップします",
        "auto_backup_failed": "自動バックアップに失敗しました",
        "auto_backup_success": "自動バックアップが正常に完了しました",
        "backup_frequency": "バックアップ頻度",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "ミニプレイヤーを閉じる",
        "combine_local_and_youtube_liked_songs": "ログイン時にお気に入りをYouTubeのいいねに置き換える",
        "combine_local_and_youtube_liked_songs_description": "YouTubeのいいねのみを使用(オフラインで曲にいいねすることはサポートされていません)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "クロスフェード (ベータ)",
        "crossfade_auto": "自動",
        "crossfade_auto_description": "BPMに基づいて自動的に期間を計算します(320kbpsストリームとBPMデータが必要です)",
        "crossfade_description": "現在のトラックをフェードアウトしながら次のトラックをフェードインすることで、曲間をスムーズに遷移します。",
        "crossfade_dj_mode": "DJスタイルトランジション",
        "crossfade_dj_mode_description": "クロスフェード中にローパスとハイパスフィルタースイープを適用して、DJのようなスムーズなトランジションを実現します",
        "crossfading": "クロスフェード処理中",
        "daily": "毎日",
        "date_range": "日付範囲",
        "desktop_player": "デスクトッププレイヤー",
        "desktop_webview_description": "Compose Multiplatformの制限により、デスクトップにWebViewを実装できません。",
        "discord_integration": "Discord統合",
        "downvote": "高評価しない",
        "enable_liquid_glass_effect_description": "一部の位置でiOSのリキッドガラスエフェクトを有効にします(Android 13+)",
        "enable_rich_presence": "リッチプレゼンスを有効にする",
        "intro_login_to_discord": "Discord Rich Presenceを有効にするためにログインしてください",
        "keep_backups": "バックアップを保持",
        "keep_backups_format": "最後の%1$sバックアップを保持",
        "keep_service_alive": "サービスを保つ",
        "keep_service_alive_description": "音楽プレイヤーサービスを活かして、システムによる終了を避けます",
        "keep_your_youtube_playlist_offline": "YouTubeプレイリストをオフラインで表示し続ける",
        "keep_your_youtube_playlist_offline_description": "YTプレイリストをローカルに保存し、オフラインで表示し続けます",
        "key": "キー",
        "last_30_days": "過去30日",
        "last_7_days": "過去7日",
        "last_90_days": "過去90日",
        "last_backup": "最後のバックアップ",
        "local_tracking_description": "リスニング履歴をローカルデータベースに記録します",
        "local_tracking_title": "ローカルリスニング履歴追跡",
        "log_in_to_discord": "Discordにログイン",
        "lower_plays": "再生",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "BetterLyricsが提供する歌詞",
        "monthly": "毎月",
        "never": "決して",
        "no_charts_found": "チャートが見つかりません",
        "no_data_analytics": "アナリティクスを表示するには、音楽を再生してください",
        "notification_channel_name": "SimpMusic再生通知",
        "open_app": "SimpMusicを開く",
        "open_blog_post": "ブログ投稿を開く",
        "open_miniplayer": "ミニプレイヤーを開く",
        "openai_api_compatible": "カスタムOpenAI互換",
        "podcasts": "ポッドキャスト",
        "prefer_320kbps_stream": "320kbpsストリームを優先",
        "prefer_320kbps_stream_description": "インターネットで利用可能な場合、自動的に320kbpsオーディオストリームを検索します",
        "proxy_password": "プロキシパスワード",
        "proxy_password_message": "プロキシパスワードを入力してください(オプション)",
        "proxy_username": "プロキシユーザー名",
        "proxy_username_message": "プロキシユーザー名を入力してください(オプション)",
        "quit_app": "アプリを終了",
        "rate_lyrics": "歌詞を評価",
        "rate_translated_lyrics": "翻訳を評価",
        "rich_presence_info": "Discordプロフィールにメディアセッション情報を表示",
        "scale": "スケール",
        "search_for": "検索",
        "seconds": "秒",
        "simpmusic_charts": "SimpMusicチャート",
        "sleep_timer_end_of_song": "スリープタイマー-曲の終わり",
        "songs_played": "再生された曲",
        "synced_playlist_cannot_change_order": "同期されたプレイリストの順序は変更できません",
        "this_year": "今年",
        "top_song": "トップソング",
        "total_listened_time": "合計リスニング時間",
        "upvote": "高評価",
        "version_format": "v%1$s",
        "vote_error": "送信に失敗しました",
        "vote_for_lyrics": "歌詞に投票",
        "vote_submitted": "この歌詞に投票いただきありがとうございます!",
        "weekly": "毎週",
        "your_320kbps_url": "あなたの320kbps URL",
        "your_recently_played": "最近再生した",
        "your_top_albums": "トップアルバム",
        "your_top_artists": "トップアーティスト",
        "your_top_tracks": "トップトラック",
        "youtube_liked_music": "YouTubeで高評価を付けた音楽"
    },
    "ko": {
        "auto_backup": "자동 백업",
        "auto_backup_description": "데이터를 자동으로 다운로드/SimpMusic 폴더에 백업하기",
        "auto_backup_failed": "자동 백업 실패",
        "auto_backup_success": "자동 백업이 성공적으로 완료되었습니다",
        "backup_frequency": "백업 빈도",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "미니 플레이어 닫기",
        "combine_local_and_youtube_liked_songs": "로그인 시 좋아요를 YouTube 좋아요로 바꾸기",
        "combine_local_and_youtube_liked_songs_description": "YouTube 좋아요만 사용 (오프라인에서 곡 좋아요 지원 안 함)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "크로스페이드 (베타)",
        "crossfade_auto": "자동",
        "crossfade_auto_description": "BPM을 기반으로 지속 시간 자동 계산 (320kbps 스트림 및 BPM 데이터 필요)",
        "crossfade_description": "현재 곡을 페이드아웃하면서 다음 곡을 페이드인하여 곡 사이에 부드러운 전환을 수행합니다.",
        "crossfade_dj_mode": "DJ 스타일 전환",
        "crossfade_dj_mode_description": "크로스페이드 중에 로우패스 및 하이패스 필터 스윕을 적용하여 더 부드러운 DJ 스타일 전환을 만듭니다",
        "crossfading": "크로스페이드 진행 중",
        "daily": "매일",
        "date_range": "날짜 범위",
        "desktop_player": "데스크톱 플레이어",
        "desktop_webview_description": "Compose Multiplatform의 제한으로 인해 데스크톱에서 WebView를 구현할 수 없습니다.",
        "discord_integration": "Discord 통합",
        "downvote": "싫어요",
        "enable_liquid_glass_effect_description": "일부 위치에서 iOS의 액체 유리 효과 활성화 (Android 13+)",
        "enable_rich_presence": "Rich Presence 활성화",
        "intro_login_to_discord": "Discord Rich Presence를 활성화하려면 로그인하세요",
        "keep_backups": "백업 유지",
        "keep_backups_format": "마지막 %1$s개 백업 유지",
        "keep_service_alive": "서비스 유지",
        "keep_service_alive_description": "음악 플레이어 서비스를 활성 상태로 유지하여 시스템에서 종료되는 것을 방지합니다",
        "keep_your_youtube_playlist_offline": "YouTube 재생목록을 오프라인에서도 표시",
        "keep_your_youtube_playlist_offline_description": "YT 재생목록을 로컬에 저장하고 오프라인에서도 표시합니다",
        "key": "키",
        "last_30_days": "지난 30일",
        "last_7_days": "지난 7일",
        "last_90_days": "지난 90일",
        "last_backup": "마지막 백업",
        "local_tracking_description": "로컬 데이터베이스에 청취 기록 기록",
        "local_tracking_title": "로컬 청취 기록 추적",
        "log_in_to_discord": "Discord에 로그인",
        "lower_plays": "재생",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "BetterLyrics에서 제공하는 가사",
        "monthly": "매월",
        "never": "절대",
        "no_charts_found": "차트를 찾을 수 없습니다",
        "no_data_analytics": "분석을 보려면 음악을 재생하세요",
        "notification_channel_name": "SimpMusic 재생 알림",
        "open_app": "SimpMusic 열기",
        "open_blog_post": "블로그 게시물 열기",
        "open_miniplayer": "미니 플레이어 열기",
        "openai_api_compatible": "사용자 정의 OpenAI 호환",
        "podcasts": "팟캐스트",
        "prefer_320kbps_stream": "320kbps 스트림 선호",
        "prefer_320kbps_stream_description": "인터넷에서 사용 가능한 경우 자동으로 320kbps 오디오 스트림을 검색합니다",
        "proxy_password": "프록시 비밀번호",
        "proxy_password_message": "프록시 비밀번호를 입력하세요 (선택 사항)",
        "proxy_username": "프록시 사용자 이름",
        "proxy_username_message": "프록시 사용자 이름을 입력하세요 (선택 사항)",
        "quit_app": "앱 종료",
        "rate_lyrics": "가사 평가",
        "rate_translated_lyrics": "번역 평가",
        "rich_presence_info": "Discord 프로필에 미디어 세션 정보 표시",
        "scale": "규모",
        "search_for": "검색",
        "seconds": "초",
        "simpmusic_charts": "SimpMusic 차트",
        "sleep_timer_end_of_song": "수면 타이머 - 곡 끝",
        "songs_played": "재생된 곡",
        "synced_playlist_cannot_change_order": "동기화된 재생목록의 순서를 변경할 수 없습니다",
        "this_year": "올해",
        "top_song": "인기곡",
        "total_listened_time": "총 청취 시간",
        "upvote": "좋아요",
        "version_format": "v%1$s",
        "vote_error": "제출 실패",
        "vote_for_lyrics": "가사에 투표",
        "vote_submitted": "이 가사에 투표해주셔서 감사합니다!",
        "weekly": "주간",
        "your_320kbps_url": "당신의 320kbps URL",
        "your_recently_played": "최근 재생",
        "your_top_albums": "상위 앨범",
        "your_top_artists": "상위 아티스트",
        "your_top_tracks": "상위 곡",
        "youtube_liked_music": "YouTube에서 좋아한 음악"
    },
    "zh": {
        "auto_backup": "自动备份",
        "auto_backup_description": "自动将数据备份到下载/SimpMusic文件夹",
        "auto_backup_failed": "自动备份失败",
        "auto_backup_success": "自动备份已成功完成",
        "backup_frequency": "备份频率",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "关闭迷你播放器",
        "combine_local_and_youtube_liked_songs": "登录时用YouTube喜欢的内容替换收藏夹",
        "combine_local_and_youtube_liked_songs_description": "仅使用YouTube喜欢的内容(离线时不支持喜欢一首歌)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "交叉淡化(测试版)",
        "crossfade_auto": "自动",
        "crossfade_auto_description": "根据BPM自动计算持续时间(需要320kbps流和BPM数据)",
        "crossfade_description": "通过淡出当前曲目同时淡入下一首曲目，实现歌曲之间的平滑过渡。",
        "crossfade_dj_mode": "DJ风格过渡",
        "crossfade_dj_mode_description": "在交叉淡化过程中应用低通和高通滤波器扫描,以实现更平滑的DJ风格过渡",
        "crossfading": "交叉淡化进行中",
        "daily": "每日",
        "date_range": "日期范围",
        "desktop_player": "桌面播放器",
        "desktop_webview_description": "由于Compose Multiplatform的限制,我无法在桌面上实现WebView。",
        "discord_integration": "Discord集成",
        "downvote": "不喜欢",
        "enable_liquid_glass_effect_description": "在某些位置启用iOS液体玻璃效果(Android 13+)",
        "enable_rich_presence": "启用Rich Presence",
        "intro_login_to_discord": "登录以启用Discord Rich Presence",
        "keep_backups": "保留备份",
        "keep_backups_format": "保留最后%1$s个备份",
        "keep_service_alive": "保持服务活跃",
        "keep_service_alive_description": "保持音乐播放器服务活跃,以避免被系统杀死",
        "keep_your_youtube_playlist_offline": "离线时保持显示YouTube播放列表",
        "keep_your_youtube_playlist_offline_description": "本地保存YT播放列表,离线时继续显示",
        "key": "密钥",
        "last_30_days": "最近30天",
        "last_7_days": "最近7天",
        "last_90_days": "最近90天",
        "last_backup": "最后备份",
        "local_tracking_description": "将您的收听历史记录到本地数据库",
        "local_tracking_title": "本地收听历史追踪",
        "log_in_to_discord": "登录Discord",
        "lower_plays": "播放",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "由BetterLyrics提供的歌词",
        "monthly": "每月",
        "never": "从不",
        "no_charts_found": "未找到图表",
        "no_data_analytics": "请播放一些音乐以查看分析",
        "notification_channel_name": "SimpMusic播放通知",
        "open_app": "打开SimpMusic",
        "open_blog_post": "打开博客文章",
        "open_miniplayer": "打开迷你播放器",
        "openai_api_compatible": "自定义OpenAI兼容",
        "podcasts": "播客",
        "prefer_320kbps_stream": "首选320kbps流",
        "prefer_320kbps_stream_description": "当互联网上可用时,自动搜索320kbps音频流。如果未找到,则回退到默认质量。",
        "proxy_password": "代理密码",
        "proxy_password_message": "请输入您的代理密码(可选)",
        "proxy_username": "代理用户名",
        "proxy_username_message": "请输入您的代理用户名(可选)",
        "quit_app": "退出应用",
        "rate_lyrics": "评价歌词",
        "rate_translated_lyrics": "评价翻译",
        "rich_presence_info": "在Discord个人资料上显示媒体会话信息",
        "scale": "规模",
        "search_for": "搜索",
        "seconds": "秒",
        "simpmusic_charts": "SimpMusic图表",
        "sleep_timer_end_of_song": "睡眠计时器 - 歌曲结束",
        "songs_played": "播放的歌曲",
        "synced_playlist_cannot_change_order": "无法更改同步播放列表的顺序",
        "this_year": "今年",
        "top_song": "热门歌曲",
        "total_listened_time": "总收听时间",
        "upvote": "喜欢",
        "version_format": "v%1$s",
        "vote_error": "提交失败",
        "vote_for_lyrics": "为歌词投票",
        "vote_submitted": "感谢您对这些歌词的投票!",
        "weekly": "每周",
        "your_320kbps_url": "您的320kbps URL",
        "your_recently_played": "最近播放",
        "your_top_albums": "您最喜欢的专辑",
        "your_top_artists": "您最喜欢的艺术家",
        "your_top_tracks": "您最喜欢的歌曲",
        "youtube_liked_music": "YouTube上喜欢的音乐"
    }
}

def add_missing_strings(filepath, lang_translations):
    """Add missing strings to XML file"""
    try:
        tree = ET.parse(filepath)
        root = tree.getroot()
        
        existing_keys = set()
        for elem in root.findall('string'):
            existing_keys.add(elem.get('name'))
        
        added = 0
        for key, value in lang_translations.items():
            if key not in existing_keys:
                string_elem = ET.SubElement(root, 'string')
                string_elem.set('name', key)
                string_elem.text = value
                added += 1
        
        tree.write(filepath, encoding='utf-8', xml_declaration=True)
        return added
    except Exception as e:
        print(f"Error: {e}")
        return 0

base_path = Path("C:/Users/kIrik/desktop/py/simpmusic/SimpMusic/composeApp/src/commonMain/composeResources")

print("Batch updating remaining 10 languages...\n")

for lang_code, translations in TRANSLATIONS_PART2.items():
    xml_file = base_path / f"values-{lang_code}" / "strings.xml"
    if xml_file.exists():
        added = add_missing_strings(xml_file, translations)
        print(f"✓ {lang_code}: Added {added} strings")

print("\n✓ All 86 translations added to 13 languages (es, it, ru, pt, ja, ko, zh)!")
