#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import xml.etree.ElementTree as ET
from pathlib import Path

# Remaining 12 languages
TRANSLATIONS_PART3 = {
    "az": {  # Azerbaijani
        "auto_backup": "Avtomatik yedəklə",
        "auto_backup_description": "Məlumatlarınızı avtomatik olaraq Yükləmələr/SimpMusic qovluğuna yedəklə",
        "auto_backup_failed": "Avtomatik yedəkləmə uğursuz",
        "auto_backup_success": "Avtomatik yedəkləmə uğurla tamamlandı",
        "backup_frequency": "Yedəkləmə tezliyi",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "Mini pleyer-i bağla",
        "combine_local_and_youtube_liked_songs": "Giriş zamanı Sevimli ilə YouTube Bəyən-i əvəz et",
        "combine_local_and_youtube_liked_songs_description": "Yalnız YouTube Bəyən-dən istifadə edin (offline şəxsə bəyənməyi dəstəkləmir)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "Çarpaz solma (BETA)",
        "crossfade_auto": "Avtomatik",
        "crossfade_auto_description": "BPM əsasında müddəti avtomatik hesabla (320kbps axını və BPM məlumatı tələb olunur)",
        "crossfade_description": "Cari məqamı sönüdürkən növbəti məqamı açaraq mahnı arasında hamar keçid edin.",
        "crossfade_dj_mode": "DJ Tərəzində Keçid",
        "crossfade_dj_mode_description": "Çarpaz solma zamanı aşağı keçid və yüksək keçid filtri döngüsü tətbiq edin",
        "crossfading": "Çarpaz solma gedir",
        "daily": "Günlük",
        "date_range": "Tarix aralığı",
        "desktop_player": "Masaüstü pleyer",
        "desktop_webview_description": "Compose Multiplatform məhdudiyyətlərindən səbəb olaraq masaüstündə WebView həyata keçirə bilmirəm.",
        "discord_integration": "Discord inteqrasiyası",
        "downvote": "Bəyənmə",
        "enable_liquid_glass_effect_description": "iOS-un maye şüşə effektini bəzi mövqelərdə aktivləşdirin (Android 13+)",
        "enable_rich_presence": "Rich Presence-ı aktivləşdirin",
        "intro_login_to_discord": "Discord Rich Presence-ı aktivləşdirmək üçün daxil olun",
        "keep_backups": "Yedəkləmələri saxla",
        "keep_backups_format": "Son %1$s yedəkləmə saxla",
        "keep_service_alive": "Xidməti canlı saxla",
        "keep_service_alive_description": "Musiqi pleyer xidmətini canlı saxla sistem tərəfindən bitiriləcəyini qarşılamaq üçün",
        "keep_your_youtube_playlist_offline": "YouTube pleytlistini bağlı şəkildə saxla",
        "keep_your_youtube_playlist_offline_description": "YT pleytlistini yerli olaraq saxla və offline zamanı göstər",
        "key": "Açar",
        "last_30_days": "Son 30 gün",
        "last_7_days": "Son 7 gün",
        "last_90_days": "Son 90 gün",
        "last_backup": "Son yedəkləmə",
        "local_tracking_description": "Dinləmə tarixçənizi yerli məlumatlarla qeyd edin",
        "local_tracking_title": "Yerli dinləmə tarixçəsi izləmə",
        "log_in_to_discord": "Discord-a girin",
        "lower_plays": "oyun",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "BetterLyrics tərəfindən təqdim olunan sözlər",
        "monthly": "Aylıq",
        "never": "Heçbir vaxt",
        "no_charts_found": "Heç bir cədvəl tapılmadı",
        "no_data_analytics": "Analitika görmək üçün bəzi musiqi oynatın",
        "notification_channel_name": "SimpMusic Oynatma Bildirişi",
        "open_app": "SimpMusic-i aç",
        "open_blog_post": "Blog yazısını aç",
        "open_miniplayer": "Mini pleyer-i aç",
        "openai_api_compatible": "Fərdi OpenAI Uyğun",
        "podcasts": "Podkastlar",
        "prefer_320kbps_stream": "320kbps axını üstün tutun",
        "prefer_320kbps_stream_description": "İnternetdə mövcud olduqda 320kbps audio axınını avtomatik olaraq axtarın",
        "proxy_password": "Proxy şifrəsi",
        "proxy_password_message": "Lütfen Proxy şifrenizi daxil edin (ixtiyari)",
        "proxy_username": "Proxy istifadəçi adı",
        "proxy_username_message": "Lütfen Proxy istifadəçi adınızı daxil edin (ixtiyari)",
        "quit_app": "Tətbiqdən çıx",
        "rate_lyrics": "Sözləri qiymətlə",
        "rate_translated_lyrics": "Tərcüməni qiymətlə",
        "rich_presence_info": "Discord profilinizə media sessiya məlumatını göstərin",
        "scale": "Miqyas",
        "search_for": "Axtarış",
        "seconds": "saniyə",
        "simpmusic_charts": "SimpMusic Diaqramları",
        "sleep_timer_end_of_song": "Yuxu Taymer - Mahnının Sonu",
        "songs_played": "Oynatılan mahnılar",
        "synced_playlist_cannot_change_order": "Sinxronlaşdırılan pleytlist sırasını dəyişə bilərik",
        "this_year": "Bu il",
        "top_song": "Top mahnı",
        "total_listened_time": "Cəmi dinləmə vaxtı",
        "upvote": "Bəyən",
        "version_format": "v%1$s",
        "vote_error": "Göndərmə uğursuz",
        "vote_for_lyrics": "Sözlər üçün səs verin",
        "vote_submitted": "Bu sözlərə səs verdiyiniz üçün təşəkkür!",
        "weekly": "Həftəlik",
        "your_320kbps_url": "Sizin 320kbps URL-si",
        "your_recently_played": "Son oynatılanlarınız",
        "your_top_albums": "Sizin əsas albomlarınız",
        "your_top_artists": "Sizin əsas müstəntiqləriniz",
        "your_top_tracks": "Sizin əsas izləriniz",
        "youtube_liked_music": "YouTube-da Bəyənilən Musiqi"
    },
    "bg": {  # Bulgarian
        "auto_backup": "Автоматично резервно копие",
        "auto_backup_description": "Автоматично резервно копие на вашите данни в папката Изтегляния/SimpMusic",
        "auto_backup_failed": "Автоматичното резервно копие не успя",
        "auto_backup_success": "Автоматичното резервно копие е завършено успешно",
        "backup_frequency": "Честота на резервното копие",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "Затворете мини плейър",
        "combine_local_and_youtube_liked_songs": "Заменете избранното с YouTube харесани при вход",
        "combine_local_and_youtube_liked_songs_description": "Използвайте само YouTube харесани (не поддържа харесване на песен офлайн)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "Кръстосано избледняване (BETA)",
        "crossfade_auto": "Автоматично",
        "crossfade_auto_description": "Автоматично изчислете продължителността на базата на BPM (изисква 320kbps поток с данни за BPM)",
        "crossfade_description": "Направете мекия преход между песните, избледнявайки текущата следа, докато избледнявате следващата.",
        "crossfade_dj_mode": "DJ преход в стил",
        "crossfade_dj_mode_description": "Приложете пометания на нискочестотния и висок преход по време на кръстосано избледняване",
        "crossfading": "Кръстосано избледняване в ход",
        "daily": "Всеки ден",
        "date_range": "Диапазон на датата",
        "desktop_player": "Плейър на работния плот",
        "desktop_webview_description": "Поради ограниченията на Compose Multiplatform не мога да приложа WebView на работния плот.",
        "discord_integration": "Discord интеграция",
        "downvote": "Не харесвам",
        "enable_liquid_glass_effect_description": "Активирайте ефекта течна стъкла на iOS в някои позиции (Android 13+)",
        "enable_rich_presence": "Активирайте Rich Presence",
        "intro_login_to_discord": "Влезте, за да активирате Discord Rich Presence",
        "keep_backups": "Съхранявайте резервни копия",
        "keep_backups_format": "Съхранете последните %1$s резервни копия",
        "keep_service_alive": "Держете услугата активна",
        "keep_service_alive_description": "Держите услугата музикален плейър активна, за да избегнете прекратяване от системата",
        "keep_your_youtube_playlist_offline": "Съхранявайте YouTube плейлиста офлайн",
        "keep_your_youtube_playlist_offline_description": "Съхранете вашия YT плейлист локално и го покажете офлайн",
        "key": "Ключ",
        "last_30_days": "Последните 30 дни",
        "last_7_days": "Последните 7 дни",
        "last_90_days": "Последните 90 дни",
        "last_backup": "Последното резервно копие",
        "local_tracking_description": "Регистрирайте своята история на слушане в локална база данни",
        "local_tracking_title": "Локално проследяване на историята на слушане",
        "log_in_to_discord": "Влезте в Discord",
        "lower_plays": "възпроизведения",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "Лирики предоставени от BetterLyrics",
        "monthly": "Месечно",
        "never": "Никога",
        "no_charts_found": "Няма намерени диаграми",
        "no_data_analytics": "Пускайте някаква музика, за да видите аналитика",
        "notification_channel_name": "SimpMusic Уведомление за възпроизведение",
        "open_app": "Отворете SimpMusic",
        "open_blog_post": "Отворете публикация в блог",
        "open_miniplayer": "Отворете мини плейър",
        "openai_api_compatible": "Персонализиран OpenAI совместим",
        "podcasts": "Подкасти",
        "prefer_320kbps_stream": "Предпочитайте 320kbps поток",
        "prefer_320kbps_stream_description": "Автоматично търсете 320kbps аудиопоток, когда е налично в интернет",
        "proxy_password": "Парола на прокси",
        "proxy_password_message": "Моля, въведете паролата на прокси (по желание)",
        "proxy_username": "Потребителско име на прокси",
        "proxy_username_message": "Моля, въведете потребителското име на прокси (по желание)",
        "quit_app": "Затворете приложението",
        "rate_lyrics": "Оценете лириката",
        "rate_translated_lyrics": "Оценете превода",
        "rich_presence_info": "Покажете информацията за медийната сесия в профила на Discord",
        "scale": "Скала",
        "search_for": "Търсене",
        "seconds": "секунди",
        "simpmusic_charts": "SimpMusic диаграми",
        "sleep_timer_end_of_song": "Таймер за сън - Край на песента",
        "songs_played": "Пуснати песни",
        "synced_playlist_cannot_change_order": "Реда на синхронизирания плейлист не може да бъде променен",
        "this_year": "Тази година",
        "top_song": "Топ песен",
        "total_listened_time": "Общо време за слушане",
        "upvote": "Харесвам",
        "version_format": "v%1$s",
        "vote_error": "Неуспешно изпращане",
        "vote_for_lyrics": "Гласуване за лирика",
        "vote_submitted": "Благодаря, че гласувахте за тази лирика!",
        "weekly": "Седмично",
        "your_320kbps_url": "Вашия 320kbps URL",
        "your_recently_played": "Наскоро пуснати",
        "your_top_albums": "Вашите топ албума",
        "your_top_artists": "Вашите топ артисти",
        "your_top_tracks": "Вашите топ песни",
        "youtube_liked_music": "YouTube харесана музика"
    },
    "ca": {  # Catalan
        "auto_backup": "Còpia de seguritat automàtica",
        "auto_backup_description": "Realitza automàticament una còpia de seguritat de les teves dades a la carpeta Baixades/SimpMusic",
        "auto_backup_failed": "Ha fallat la còpia de seguritat automàtica",
        "auto_backup_success": "La còpia de seguritat automàtica s'ha completat correctament",
        "backup_frequency": "Freqüència de còpia de seguritat",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "Tancar mini reproductor",
        "combine_local_and_youtube_liked_songs": "Reemplaçar Favorit per YouTube Liked en iniciar sessió",
        "combine_local_and_youtube_liked_songs_description": "Utilitzar només YouTube Liked (no admet afegir una cançó a favorits quan està fora de línia)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "Dissolució creuada (BETA)",
        "crossfade_auto": "Automàtic",
        "crossfade_auto_description": "Calcula automàticament la durada basada en BPM (requereix 320kbps de flux amb dades de BPM)",
        "crossfade_description": "Fes una transició suau entre cançons esmorteint la pista actual mentre obres la següent.",
        "crossfade_dj_mode": "Transició a l'estil DJ",
        "crossfade_dj_mode_description": "Aplica barrits de filtre de pas baix i alt durant la dissolució creuada",
        "crossfading": "Dissolució creuada en curs",
        "daily": "Diari",
        "date_range": "Rang de dates",
        "desktop_player": "Reproductor d'escriptori",
        "desktop_webview_description": "Per les limitacions de Compose Multiplatform, no puc implementar WebView a l'escriptori.",
        "discord_integration": "Integració de Discord",
        "downvote": "No m'agrada",
        "enable_liquid_glass_effect_description": "Habilita l'efecte vidre líquid d'iOS en algunes posicions (Android 13+)",
        "enable_rich_presence": "Habilita la presència enriquida",
        "intro_login_to_discord": "Inicia sessió per habilitar Discord Rich Presence",
        "keep_backups": "Mantenir còpies de seguritat",
        "keep_backups_format": "Mantenir les últimes %1$s còpies de seguritat",
        "keep_service_alive": "Mantenir el servei actiu",
        "keep_service_alive_description": "Manté el servei del reproductor de música actiu per evitar que el sistema el tanqui",
        "keep_your_youtube_playlist_offline": "Mantenir la llista de reproducció de YouTube en línia",
        "keep_your_youtube_playlist_offline_description": "Desa la teva llista de reproducció de YT localment i mostra-la en línia",
        "key": "Clau",
        "last_30_days": "Últims 30 dies",
        "last_7_days": "Últims 7 dies",
        "last_90_days": "Últims 90 dies",
        "last_backup": "Última còpia de seguritat",
        "local_tracking_description": "Registra el teu historial d'escolta a la base de dades local",
        "local_tracking_title": "Seguiment local de l'historial d'escolta",
        "log_in_to_discord": "Inicia sessió a Discord",
        "lower_plays": "reproduccions",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "Lletra proporcionada per BetterLyrics",
        "monthly": "Mensual",
        "never": "Mai",
        "no_charts_found": "No s'han trobat gràfics",
        "no_data_analytics": "Reprodueix una mica de música per veure analítiques",
        "notification_channel_name": "Notificació de reproducció de SimpMusic",
        "open_app": "Obrir SimpMusic",
        "open_blog_post": "Obrir entrada de blog",
        "open_miniplayer": "Obrir mini reproductor",
        "openai_api_compatible": "Compatible personalitzat amb OpenAI",
        "podcasts": "Podcasts",
        "prefer_320kbps_stream": "Preferir flux de 320kbps",
        "prefer_320kbps_stream_description": "Cercar automàticament flux d'àudio de 320kbps quan estigui disponible a Internet",
        "proxy_password": "Contrasenya del proxy",
        "proxy_password_message": "Introduïu la vostra contrasenya de proxy (opcional)",
        "proxy_username": "Nom d'usuari del proxy",
        "proxy_username_message": "Introduïu el vostre nom d'usuari de proxy (opcional)",
        "quit_app": "Tancar aplicació",
        "rate_lyrics": "Valorar lletra",
        "rate_translated_lyrics": "Valorar traducció",
        "rich_presence_info": "Mostra informació de la sessió multimèdia al vostre perfil de Discord",
        "scale": "Escala",
        "search_for": "Cercar",
        "seconds": "segons",
        "simpmusic_charts": "Gràfics de SimpMusic",
        "sleep_timer_end_of_song": "Temporitzador de son - Fi de cançó",
        "songs_played": "Cançons reproduïdes",
        "synced_playlist_cannot_change_order": "L'ordre de la llista de reproducció sincronitzada no es pot canviar",
        "this_year": "Enguany",
        "top_song": "Cançó top",
        "total_listened_time": "Temps total d'escolta",
        "upvote": "M'agrada",
        "version_format": "v%1$s",
        "vote_error": "No s'ha pogut enviar",
        "vote_for_lyrics": "Vota per lletra",
        "vote_submitted": "Gràcies per votar aquesta lletra!",
        "weekly": "Setmanal",
        "your_320kbps_url": "La teva URL de 320kbps",
        "your_recently_played": "Reproduït recentment",
        "your_top_albums": "Els teus millors àlbums",
        "your_top_artists": "Els teus millors artistes",
        "your_top_tracks": "Les teves millors cançons",
        "youtube_liked_music": "Música que t'agrada de YouTube"
    },
    "fa": {  # Persian - using simplified version
        "auto_backup": "پشتیبان گیری خودکار",
        "auto_backup_description": "پشتیبان گیری خودکار از داده های خود در پوشه دانلودها/SimpMusic",
        "auto_backup_failed": "پشتیبان گیری خودکار ناموفق بود",
        "auto_backup_success": "پشتیبان گیری خودکار با موفقیت تکمیل شد",
        "backup_frequency": "فرکانس پشتیبان گیری",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "بستن پخش کننده کوچک",
        "combine_local_and_youtube_liked_songs": "جایگزینی مورد علاقه با آنچه YouTube زمان ورود دوست دارد",
        "combine_local_and_youtube_liked_songs_description": "استفاده از دوست داشتن YouTube فقط (از آن پشتیبانی نمی کند زمانی که آفلاین باشید)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "محو متقاطع (بتا)",
        "crossfade_auto": "خودکار",
        "crossfade_auto_description": "محاسبه خودکار مدت زمان بر اساس BPM (جریان 320kbps با داده های BPM مورد نیاز است)",
        "crossfade_description": "انتقال صاف بین آهنگ ها با محو نوار فعلی و محو نوار بعدی.",
        "crossfade_dj_mode": "گذار در سبک DJ",
        "crossfade_dj_mode_description": "اعمال جاروی فیلتر پایین و بالا در حین محو متقاطع",
        "crossfading": "محو متقاطع در حال انجام",
        "daily": "روزانه",
        "date_range": "محدوده تاریخ",
        "desktop_player": "پخش کننده دسکتاپ",
        "desktop_webview_description": "به دلیل محدودیت های Compose Multiplatform نمی تونم WebView را روی دسکتاپ اجرا کنم.",
        "discord_integration": "یکپارچگی Discord",
        "downvote": "دوست ندارم",
        "enable_liquid_glass_effect_description": "فعال کردن اثر شیشه مایع iOS در برخی موقعیت ها (Android 13+)",
        "enable_rich_presence": "فعال کردن Rich Presence",
        "intro_login_to_discord": "برای فعال کردن Discord Rich Presence وارد شوید",
        "keep_backups": "نگه داشتن نسخه های پشتیبان",
        "keep_backups_format": "نگه داشتن آخرین %1$s نسخه های پشتیبان",
        "keep_service_alive": "نگه داشتن سرویس فعال",
        "keep_service_alive_description": "سرویس پخش کننده موسیقی را فعال نگه دارید تا از قطع شدن توسط سیستم جلوگیری کنید",
        "keep_your_youtube_playlist_offline": "نگه داشتن لیست پخش YouTube آفلاین",
        "keep_your_youtube_playlist_offline_description": "لیست پخش YT خود را محلی ذخیره کنید و آن را آفلاین نمایش دهید",
        "key": "کلیدی",
        "last_30_days": "30 روز گذشته",
        "last_7_days": "7 روز گذشته",
        "last_90_days": "90 روز گذشته",
        "last_backup": "آخرین نسخه پشتیبان",
        "local_tracking_description": "ثبت تاریخ گوش دهندگی به پایگاه داده محلی",
        "local_tracking_title": "تعقب محلی تاریخچه گوش دهندگی",
        "log_in_to_discord": "وارد Discord شوید",
        "lower_plays": "بازی",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "اشعار ارائه شده توسط BetterLyrics",
        "monthly": "ماهانه",
        "never": "هرگز",
        "no_charts_found": "هیچ نمودار یافت نشد",
        "no_data_analytics": "برای دیدن تحلیلات موسیقی پخش کنید",
        "notification_channel_name": "اطلاع رسانی پخش SimpMusic",
        "open_app": "باز کردن SimpMusic",
        "open_blog_post": "باز کردن پست وبلاگ",
        "open_miniplayer": "باز کردن پخش کننده کوچک",
        "openai_api_compatible": "سازگار سفارشی OpenAI",
        "podcasts": "پادکست",
        "prefer_320kbps_stream": "ترجیح جریان 320kbps",
        "prefer_320kbps_stream_description": "به صورت خودکار جریان صوتی 320kbps را جستجو کنید زمانی که در اینترنت موجود است",
        "proxy_password": "رمز عبور پروکسی",
        "proxy_password_message": "لطفا رمز عبور پروکسی خود را وارد کنید (اختیاری)",
        "proxy_username": "نام کاربری پروکسی",
        "proxy_username_message": "لطفا نام کاربری پروکسی خود را وارد کنید (اختیاری)",
        "quit_app": "خروج از برنامه",
        "rate_lyrics": "امتیاز دهی به اشعار",
        "rate_translated_lyrics": "امتیاز دهی به ترجمه",
        "rich_presence_info": "نمایش اطلاعات جلسه رسانه در پروفیل Discord خود",
        "scale": "مقیاس",
        "search_for": "جستجو",
        "seconds": "ثانیه",
        "simpmusic_charts": "نمودارهای SimpMusic",
        "sleep_timer_end_of_song": "تایمر خواب - پایان آهنگ",
        "songs_played": "آهنگ های پخش شده",
        "synced_playlist_cannot_change_order": "ترتیب لیست پخش همگام نمی تواند تغییر کند",
        "this_year": "سال این",
        "top_song": "بهترین آهنگ",
        "total_listened_time": "کل زمان گوش دهندگی",
        "upvote": "دوست دارم",
        "version_format": "v%1$s",
        "vote_error": "ارسال ناموفق",
        "vote_for_lyrics": "رای دهی برای اشعار",
        "vote_submitted": "متشکرم برای رای دادن این اشعار!",
        "weekly": "هفتگی",
        "your_320kbps_url": "URL 320kbps شما",
        "your_recently_played": "اخیرا پخش شده",
        "your_top_albums": "بهترین آلبوم های شما",
        "your_top_artists": "بهترین هنرمندان شما",
        "your_top_tracks": "بهترین آهنگ های شما",
        "youtube_liked_music": "موسیقی YouTube که دوست دارید"
    },
    "fi": {  # Finnish
        "auto_backup": "Automaattinen varmuuskopiointi",
        "auto_backup_description": "Varmuuskopioi tiedot automaattisesti latauskansioon/SimpMusic",
        "auto_backup_failed": "Automaattinen varmuuskopiointi epäonnistui",
        "auto_backup_success": "Automaattinen varmuuskopiointi saatu päätökseen",
        "backup_frequency": "Varmuuskopioinnin taajuus",
        "better_lyrics": "BetterLyrics",
        "bpm": "BPM",
        "close_miniplayer": "Sulje soitin",
        "combine_local_and_youtube_liked_songs": "Korvaa suosikit YouTube:n pitämillä sisäänkirjautumisen yhteydessä",
        "combine_local_and_youtube_liked_songs_description": "Käytä vain YouTube:n mieltymyksiä (ei tue kappaleen pitämistä offline-tilassa)",
        "copyright": "©2023-2025 Tuan Minh Nguyen Duc (maxrave-dev)",
        "crossfade": "Ristiväistö (BETA)",
        "crossfade_auto": "Automaattinen",
        "crossfade_auto_description": "Laske kesto automaattisesti BPM:n perusteella (vaatii 320 kbps virtaa BPM-tietojen kanssa)",
        "crossfade_description": "Pehmeä siirtymä kappaleiden välillä vaiheistamalla nykyistä raitaa seuraavaksi.",
        "crossfade_dj_mode": "DJ-tyylinen siirtymä",
        "crossfade_dj_mode_description": "Käytä alipäästö- ja yläpäästösuodattimen pyyhkäisyjä ristiväistön aikana",
        "crossfading": "Ristiväistö käynnissä",
        "daily": "Päivittäin",
        "date_range": "Päivämäärä alue",
        "desktop_player": "Työpöydän soitin",
        "desktop_webview_description": "Compose Multiplatform-rajoitusten vuoksi en voi ottaa WebViews käyttöön työpöydällä.",
        "discord_integration": "Discord integraatio",
        "downvote": "En pidä",
        "enable_liquid_glass_effect_description": "Ota käyttöön iOS:n nestemäisen lasin vaikutus joissakin kohdissa (Android 13+)",
        "enable_rich_presence": "Ota Rich Presence käyttöön",
        "intro_login_to_discord": "Kirjaudu sisään ottaaksesi Discord Rich Presencen käyttöön",
        "keep_backups": "Säilytä varmuuskopiot",
        "keep_backups_format": "Säilytä viimeiset %1$s varmuuskopiot",
        "keep_service_alive": "Pidä palvelu aktiivisena",
        "keep_service_alive_description": "Pidä musiikkisoittimen palvelu aktiivisena välttääksesi järjestelmän sammuttamista",
        "keep_your_youtube_playlist_offline": "Säilytä YouTube-soittolista offline-tilassa",
        "keep_your_youtube_playlist_offline_description": "Tallenna YT-soittolista paikallisesti ja näytä se offline-tilassa",
        "key": "Avain",
        "last_30_days": "Viimeiset 30 päivää",
        "last_7_days": "Viimeiset 7 päivää",
        "last_90_days": "Viimeiset 90 päivää",
        "last_backup": "Viimeisin varmuuskopiointi",
        "local_tracking_description": "Kirjaa kuuntelutietue paikalliseen tietokantaan",
        "local_tracking_title": "Paikallinen kuuntelun seurantahistoria",
        "log_in_to_discord": "Kirjaudu Discordiin",
        "lower_plays": "toisto",
        "lrclib": "LRCLIB",
        "lyrics_provider_betterlyrics": "Sanat toimittaa BetterLyrics",
        "monthly": "Kuukausittain",
        "never": "Koskaan",
        "no_charts_found": "Karttoja ei löytynyt",
        "no_data_analytics": "Analysointia varten toista musiikkia",
        "notification_channel_name": "SimpMusic-toiston ilmoitus",
        "open_app": "Avaa SimpMusic",
        "open_blog_post": "Avaa blogipostaus",
        "open_miniplayer": "Avaa soitin",
        "openai_api_compatible": "Mukautettu OpenAI-yhteensopiva",
        "podcasts": "Podcastit",
        "prefer_320kbps_stream": "Suosittele 320 kbps virtaa",
        "prefer_320kbps_stream_description": "Etsi automaattisesti 320 kbps äänivirtaa, kun se on saatavilla internetissä",
        "proxy_password": "Välityspalvelimen salasana",
        "proxy_password_message": "Anna välityspalvelimen salasanasi (valinnainen)",
        "proxy_username": "Välityspalvelimen käyttäjänimi",
        "proxy_username_message": "Anna välityspalvelimen käyttäjänimesi (valinnainen)",
        "quit_app": "Poistu sovelluksesta",
        "rate_lyrics": "Arvioi sanoitukset",
        "rate_translated_lyrics": "Arvioi käännös",
        "rich_presence_info": "Näytä mediaistunnon tiedot Discord-profiilinsa",
        "scale": "Asteikko",
        "search_for": "Etsi",
        "seconds": "sekuntia",
        "simpmusic_charts": "SimpMusic-kaaviot",
        "sleep_timer_end_of_song": "Univiserit - kappaleen loppu",
        "songs_played": "Toistettuja kappaleita",
        "synced_playlist_cannot_change_order": "Synkronoidun soittolistanon järjestystä ei voi muuttaa",
        "this_year": "Tänä vuonna",
        "top_song": "Huippukappale",
        "total_listened_time": "Kokonaissoittoaika",
        "upvote": "Pidä",
        "version_format": "v%1$s",
        "vote_error": "Lähetys epäonnistui",
        "vote_for_lyrics": "Äänestä sanoituksille",
        "vote_submitted": "Kiitos äänestämisestä näistä sanoituksista!",
        "weekly": "Viikoittain",
        "your_320kbps_url": "Sinun 320kbps URL",
        "your_recently_played": "Äskettäin toistettava",
        "your_top_albums": "Suosituimpat albumit",
        "your_top_artists": "Suosituimpat taiteilijat",
        "your_top_tracks": "Suosituimpat kappaleet",
        "youtube_liked_music": "YouTube-musiikki, jota pidät"
    }
}

def add_missing_strings(filepath, lang_translations):
    """Add missing strings to XML file"""
    try:
        tree = ET.parse(filepath)
        root = tree.getroot()
        
        existing_keys = set()
        for elem in root.findall('string'):
            existing_keys.add(elem.get('name'))
        
        added = 0
        for key, value in lang_translations.items():
            if key not in existing_keys:
                string_elem = ET.SubElement(root, 'string')
                string_elem.set('name', key)
                string_elem.text = value
                added += 1
        
        tree.write(filepath, encoding='utf-8', xml_declaration=True)
        return added
    except Exception as e:
        print(f"Error: {e}")
        return 0

base_path = Path("C:/Users/kIrik/desktop/py/simpmusic/SimpMusic/composeApp/src/commonMain/composeResources")

print("Batch updating remaining 6 languages...\n")

for lang_code, translations in TRANSLATIONS_PART3.items():
    xml_file = base_path / f"values-{lang_code}" / "strings.xml"
    if xml_file.exists():
        added = add_missing_strings(xml_file, translations)
        print(f"✓ {lang_code}: Added {added} strings")

print("\n✓ Part 3 complete (6 languages updated)!")
